;;; publish.el --- build lameserver.net from org sources  -*- lexical-binding: t; -*-

;; The whole static-site build for https://lameserver.net — an ANSI/BBS-style
;; blog written in org-mode.  Everything under docs/ is generated by this file:
;;
;;   org/posts/NNNN-slug.org  ->  docs/phile/0xNN/index.html
;;   org/pages/about.org      ->  docs/about/index.html
;;   org/media/               ->  docs/media/
;;   assets/                  ->  docs/assets/  (static/ copied to docs/ root)
;;   + board listing, category pages, feed.xml, search.json
;;
;; Images in posts are converted to colored ANSI art at build time (chafa),
;; parsed from SGR escapes into HTML by pure elisp.  Titles and section
;; headings are set in lameblock, the site's own hand-drawn block font.
;; Missing tools degrade gracefully: no chafa -> plain <img>, no htmlize ->
;; unfontified code blocks.
;;
;; Entry points:
;;   M-x lameserver-publish        build docs/
;;   M-x lameserver-deploy         build + git add/commit/push
;;   M-x lameserver-clean          wipe docs/ + .cache/
;;   emacs --batch -l publish.el -f lameserver-publish-batch

;;; Code:

(require 'cl-lib)
(require 'ox)
(require 'ox-html)
(require 'ox-ascii)
(require 'xml)
(require 'url-util)
(require 'subr-x)

(defconst lameserver--root
  (file-name-directory (or load-file-name buffer-file-name))
  "Repository root, derived from this file's location.")

(defconst lameserver--site-url "https://lameserver.net")
(defconst lameserver--site-name "lameserver")
(defconst lameserver--converter-version "v2"
  "Bump to invalidate every cached ANSI conversion.")

(defvar lameserver--gpg-key "44DF29BCAD9943D8"
  "Key philes are signed with (grim@samhain.su).  Nil = gpg default key.")

(defconst lameserver--ansi-width 76 "Default chafa width in cells.")
(defconst lameserver--ansi-max-width 120)
(defconst lameserver--thumb-size "24x12")
(defconst lameserver--ansi-warn-bytes 300000)

(defconst lameserver--dividers
  ["·   ░ ▒▒ ░░▒▓▒░ ▒ ░   ·    ."
   "─── ─────────── ░▒▓▒░ ── ─ ·"
   "▄▄▄▄▄▄▓▓▒▒░░ ·    ·\n   ▀▀▓▒░ ·"
   ".  · ▀▄▀▄ ░▒░ ▄▀▄▀ ·  ."
   "░▒▓██▓▒░ · ▒█▓ ░▓ ▒ ░  ·"
   "· x ░ xx ▒░ x ░░ ·  x  ."
   "─ ── ▄██▓▒░ ·∙ .   ─ ─"]
  "Per-post divider strings, artscene style (multi-line via \\n);
one is picked deterministically per phile.")

(defconst lameserver--emblem-classes
  ["dc-cyan" "dc-green" "dc-orange" "dc-pink" "dc-purple" "dc-red" "dc-yellow"]
  "Dracula color classes used by procedural emblems (defined in site.css).")

(defvar lameserver--manifest nil
  "List of post plists, sorted by phile number descending (newest first).")

(defvar lameserver--build-stamp nil
  "Human-readable stamp for the footer, set once per build.")

;;;; ---------------------------------------------------------------- paths

(defun lameserver--path (&rest parts)
  (expand-file-name (string-join parts "/") lameserver--root))

(defun lameserver--docs (&rest parts)
  (apply #'lameserver--path "docs" parts))

(defun lameserver--cache (&rest parts)
  (let ((f (apply #'lameserver--path ".cache" parts)))
    (make-directory (file-name-directory f) t)
    f))

;;;; ---------------------------------------------------------------- logging

(defun lameserver--log (fmt &rest args)
  (let ((msg (apply #'format fmt args)))
    (with-current-buffer (get-buffer-create "*lameserver-log*")
      (goto-char (point-max))
      (insert msg "\n"))
    (if noninteractive (princ (concat msg "\n")) (message "%s" msg))))

;;;; ---------------------------------------------------------------- tools

(defvar lameserver--tools (make-hash-table :test 'equal))

(defun lameserver--tool (name)
  "Return the executable for NAME, nil if absent (memoized per session)."
  (let ((hit (gethash name lameserver--tools 'miss)))
    (if (eq hit 'miss)
        (puthash name (executable-find name) lameserver--tools)
      hit)))

(defun lameserver--run (program &rest args)
  "Run PROGRAM with ARGS; return stdout string, or nil on failure (logged)."
  (with-temp-buffer
    (let ((status (apply #'call-process program nil t nil args)))
      (if (and (numberp status) (zerop status))
          (buffer-string)
        (lameserver--log "lameserver: %s %s failed (%s): %s"
                         program (string-join args " ") status
                         (string-trim (buffer-string)))
        nil))))

;;;; ---------------------------------------------------------------- misc

(defun lameserver--slugify (s)
  (string-trim (replace-regexp-in-string
                "[^a-z0-9]+" "-" (downcase s)) "-+" "-+"))

(defun lameserver--escape (s)
  (xml-escape-string (or s "")))

(defun lameserver--phile-hex (n) (format "0x%02x" n))

(defun lameserver--seed (string bits)
  "Deterministic integer in [0,BITS) from STRING."
  (mod (string-to-number (substring (secure-hash 'sha1 string) 0 8) 16) bits))

(defun lameserver--xorshift (state)
  "One xorshift32 step; returns new 32-bit STATE."
  (let ((s state))
    (setq s (logand #xffffffff (logxor s (ash s 13))))
    (setq s (logand #xffffffff (logxor s (ash s -17))))
    (setq s (logand #xffffffff (logxor s (ash s 5))))
    (if (zerop s) 88172645463325252 s)))

;;;; ---------------------------------------------------------------- manifest

(defconst lameserver--kw-re
  "^#\\+\\(TITLE\\|DATE\\|FILETAGS\\|PHILE\\|THUMB\\|DESCRIPTION\\|DRAFT\\):[ \t]*\\(.*?\\)[ \t]*$")

(defun lameserver--read-keywords (file)
  "Scan FILE's preamble for keywords; also record first image and word count."
  (with-temp-buffer
    (insert-file-contents file)
    (let ((kw '()) first-image)
      (save-excursion
        (let ((case-fold-search t))
          (while (re-search-forward lameserver--kw-re nil t)
            (push (cons (upcase (match-string 1)) (match-string 2)) kw))))
      (save-excursion
        (when (re-search-forward
               "\\[\\[file:\\([^]]+\\.\\(?:png\\|jpe?g\\|gif\\|webp\\)\\)\\]"
               nil t)
          (setq first-image (match-string 1))))
      (let ((words (count-words (point-min) (point-max))))
        (list :keywords kw :first-image first-image :words words)))))

(defun lameserver--scan-posts ()
  "Build `lameserver--manifest' from org/posts/*.org."
  (let ((entries '()))
    (dolist (file (directory-files (lameserver--path "org/posts") t "\\.org\\'"))
      (let* ((scan (lameserver--read-keywords file))
             (kw (plist-get scan :keywords))
             (get (lambda (k) (cdr (assoc k kw))))
             (title (or (funcall get "TITLE")
                        (file-name-base file)))
             (phile-raw (funcall get "PHILE"))
             (phile (and phile-raw (string-to-number
                                    (string-remove-prefix "0x" phile-raw) 16)))
             (date (funcall get "DATE"))
             (tags (and (funcall get "FILETAGS")
                        (split-string (funcall get "FILETAGS") ":" t "[ \t]+")))
             ;; #+DRAFT: t marks a draft; absent or nil/no/false/0 publishes
             (draft (let ((v (funcall get "DRAFT")))
                      (and v (not (member (downcase v)
                                          '("" "nil" "no" "false" "0")))))))
        (unless phile
          (error "lameserver: %s has no #+PHILE: keyword" file))
        (push (list :file file
                    :phile phile
                    :phile-hex (lameserver--phile-hex phile)
                    :slug (lameserver--slugify title)
                    :title title
                    :date date
                    :time (and date (ignore-errors (org-time-string-to-time date)))
                    :tags tags
                    :description (or (funcall get "DESCRIPTION") "")
                    :thumb (funcall get "THUMB")
                    :first-image (plist-get scan :first-image)
                    :words (plist-get scan :words)
                    :draft draft
                    :url (format "%s/phile/%s/" lameserver--site-url
                                 (lameserver--phile-hex phile)))
              entries)))
    ;; duplicates are a hard error before anything is written
    (let ((seen (make-hash-table)))
      (dolist (e entries)
        (let ((n (plist-get e :phile)))
          (when (gethash n seen)
            (error "lameserver: duplicate phile number %s (%s and %s)"
                   (lameserver--phile-hex n)
                   (plist-get (gethash n seen) :file) (plist-get e :file)))
          (puthash n e seen))))
    (setq lameserver--manifest
          (sort entries (lambda (a b) (> (plist-get a :phile)
                                         (plist-get b :phile)))))))

(defun lameserver--published ()
  "Manifest entries that are not drafts, newest first."
  (cl-remove-if (lambda (e) (plist-get e :draft)) lameserver--manifest))

(defun lameserver--manifest-entry (file)
  (cl-find (file-truename file) lameserver--manifest
           :key (lambda (e) (file-truename (plist-get e :file)))
           :test #'equal))

(defun lameserver--divider (entry)
  (aref lameserver--dividers
        (lameserver--seed (concat (plist-get entry :phile-hex)
                                  (plist-get entry :slug))
                          (length lameserver--dividers))))

;;;; ---------------------------------------------------------------- lameblock

;; A hand-drawn block font in the artscene tradition — CP437 blocks only
;; (▀ ▄ █ ▌ ▐ ░ ▒ ▓), four rows tall, thick strokes.  No figlet: these
;; letterforms are the site's own.  Rendered with per-letter shade
;; alternation and a darker bottom row, one hue family per piece.

(defconst lameserver--lameblock
  '((?a "▄████▄ " "▄▄▄▄▐█▌" "██▀▀▐█▌" "▀████▀ ")
    (?b "██▄▄▄  " "██▀▀██▄" "██  ▐██" "██████▀")
    (?c "▄████▄" "██▌ ▀▀" "██▌ ▄▄" "▀████▀")
    (?d "  ▄▄▄██" "▄██▀▀██" "██▌ ▐██" "▀██████")
    (?e "▄████▄ " "██▄▄▄██" "██▌▀▀▀▀" "▀█████▌")
    (?f " ▄███▄" "▐█▌▀▀ " "████  " "▐█▌   ")
    (?g "▄████▄" "██▄▄██" "▀▀▀▐██" "▄███▀ ")
    (?h "██▄▄▄  " "██▀▀██▄" "██  ▐██" "██  ▐██")
    (?i "▐█▌" "▄▄ " "██▌" "██▌")
    (?j "  ▐█▌" "  ▄▄ " "  ██▌" "▀██▀ ")
    (?k "██ ▄█▌" "██▄█▀ " "████▄ " "██ ▀█▌")
    (?l "██▌ " "██▌ " "██▌ " "▀██▄")
    (?m "▄█▄▄█▄▄ " "██▀██▀██" "██ ██ ██" "██ ██ ██")
    (?n "▄█▄██▄ " "███▀▐██" "██▌ ▐██" "██▌ ▐██")
    (?o "▄████▄ " "██▌ ▐██" "██▌ ▐██" "▀████▀ ")
    (?p "▄█████▄" "██▌ ▐██" "██████▀" "██▌    ")
    (?q "▄█████▌" "██▌ ██▌" "▀█████▌" "   ▐██▌")
    (?r "▄█▄███▄" "███▀▀▀ " "██▌    " "██▌    ")
    (?s "▄████▄" "██▄▄▄ " "▀▀▀██▌" "█████▀")
    (?t " ▄█▄  " "▀███▀ " " ██▌  " " ▀██▄ ")
    (?u "██  ██" "██  ██" "██  ██" "▀████▀")
    (?v "██▌ ▐██" "██▌ ▐██" "▐██▄██▌" " ▀███▀ ")
    (?w "██ ██ ██" "██ ██ ██" "██▄██▄██" "▀██▀▀██▀")
    (?x "▐█▄▄█▌" " ▀██▀ " " ▄██▄ " "▐█▀▀█▌")
    (?y "██▌▐██" "▐████▌" "  ██▌ " " ▐█▌  ")
    (?z "█████▌" "  ▄█▀ " " ▄█▀▄▄" "█████▌")
    (?0 "▄████▄" "██▌▄██" "██▀▐██" "▀████▀")
    (?1 "▄██▌" " ██▌" " ██▌" "▄███▄")
    (?2 "▄███▄ " "▀▀▐██▌" " ▄█▀  " "█████▌")
    (?3 "▄███▄ " " ▄▄██▀" " ▀▀▐█▌" "▀███▀ ")
    (?4 "▄█▌▐█▌" "██▄▄██" "▀▀▀▐█▌" "   ▐█▌")
    (?5 "█████▌" "██▄▄▄ " "▀▀▀██▌" "████▀ ")
    (?6 "▄███▄ " "██▄▄▄ " "██▀▐█▌" "▀███▀ ")
    (?7 "█████▌" "  ▄█▀ " " ▐█▌  " " ██▌  ")
    (?8 "▄███▄ " "▐█▄▄█▌" "██▀▀██" "▀███▀ ")
    (?9 "▄███▄ " "██ ▐█▌" "▀▀▀▐█▌" " ███▀ ")
    (?? "▄███▄ " "▀▀▐██▌" "  ██  " "  ▄▄  ")
    (?: " " "▄" " " "▄")
    (?& "▄██▄  " "▐█▄█▌ " "██▀█▄█" "▀██▄█▌")
    (?, " " " " "▄" "▀")
    (?. " " " " " " "▄")
    (?! "█▌" "█▌" "▀ " "▄ ")
    (?' "█▌" "▀ " " " " ")
    (?- "  " "▄▄" "  " "  ")
    (?\s "  " "  " "  " "  "))
  "The lameblock font: (CHAR ROW1 ROW2 ROW3 ROW4).")

(defconst lameserver--hues ["pink" "purple" "cyan" "green" "orange"]
  "Accent hue families; each phile gets one, seeded from its number.")

(defun lameserver--hue (entry)
  (aref lameserver--hues
        (lameserver--seed (concat "hue" (plist-get entry :phile-hex)
                                  (plist-get entry :slug))
                          (length lameserver--hues))))

(defun lameserver--block-glyph (ch)
  (cdr (assq (downcase ch) lameserver--lameblock)))

(defun lameserver--block-words (text)
  "TEXT as a list of words; each word is (WIDTH . GLYPH-LIST)."
  (let ((words '()))
    (dolist (word (split-string (downcase text) " " t))
      (let ((glyphs (delq nil (mapcar #'lameserver--block-glyph
                                      (string-to-list word)))))
        (when glyphs
          (push (cons (apply #'+ (mapcar (lambda (g)
                                           (apply #'max (mapcar #'length g)))
                                         glyphs))
                      glyphs)
                words))))
    (nreverse words)))

(defun lameserver--block-logo (text &optional hue max-cols)
  "TEXT in the lameblock font: a <pre> of shaded letterforms.
HUE names the accent family (nil = newsletter gray); wraps at MAX-COLS."
  (let* ((max-cols (or max-cols 64))
         (space-w 3)
         (lines '())     ; bands of words
         (line '()) (line-w 0)
         (letter -1))
    (dolist (word (lameserver--block-words text))
      (let ((w (car word)))
        (when (and line (> (+ line-w space-w w) max-cols))
          (push (nreverse line) lines)
          (setq line '() line-w 0))
        (push word line)
        (setq line-w (+ line-w (if (cdr line) space-w 0) w))))
    (when line (push (nreverse line) lines))
    (setq lines (nreverse lines))
    (let* ((width (apply #'max 1 (mapcar
                                  (lambda (l)
                                    (+ (apply #'+ (mapcar #'car l))
                                       (* space-w (1- (length l)))))
                                  lines)))
           (out '()))
      (dolist (l lines)
        ;; letters alternate two shades of the hue; the counter runs
        ;; per band so all four rows of a glyph agree
        (let ((band-start (1+ letter)))
          (dotimes (row 4)
            (let ((cells '()) (li (1- band-start)))
              (dolist (word l)
                (unless (eq word (car l))
                  (push (make-string space-w ?\s) cells))
                (dolist (g (cdr word))
                  (cl-incf li)
                  (let* ((line-str (nth row g))
                         (gw (apply #'max (mapcar #'length g)))
                         (padded (concat line-str
                                         (make-string (- gw (length line-str)) ?\s))))
                    (push (format "<span class=\"%s\">%s</span>"
                                  (cond ((= row 3) "sh")
                                        ((cl-evenp li) "hi")
                                        (t "lo"))
                                  (lameserver--escape padded))
                          cells))))
              (when (= row 3) (setq letter li))
              (push (apply #'concat (nreverse cells)) out)))))
      ;; a dust line under the piece, seeded from the text
      (let ((state (string-to-number
                    (substring (secure-hash 'sha1 text) 0 8) 16))
            (dust '()))
        (dotimes (_ width)
          (setq state (lameserver--xorshift state))
          (push (aref "  ·  ░ ▒  ▀ ▄   .      " (mod state 23)) dust))
        (push (format "<span class=\"sh\">%s</span>"
                      (apply #'string (nreverse dust)))
              out))
      (format "<pre class=\"lb%s\" style=\"--cols:%d\" aria-hidden=\"true\">%s</pre>"
              (if hue (concat " hue-" hue) "")
              width
              (string-join (nreverse out) "\n")))))

;;;; ---------------------------------------------------------------- drip edge

;; The file_id.diz melt: a solid mass along the top that drips down into
;; ░▒▓ hangers of clustered, irregular length.  Wider than any viewport so
;; it clips at the box edge.  Rendered as one <pre>; four rows.

(defconst lameserver--drip-cols 220 "Drip width in cells; clips to the box.")

(defun lameserver--drip (&optional seed-string)
  "A drip edge <pre>, its hangers seeded deterministically from SEED-STRING."
  (let* ((cols lameserver--drip-cols)
         (seed (or seed-string "drip"))
         (state (string-to-number (substring (secure-hash 'sha1 seed) 0 8) 16))
         (heights (make-vector cols 0))
         (cur 1)
         (rows '()))
    (when (zerop state) (setq state 305419896))
    ;; a smoothed random walk of hanger lengths (0..3), with occasional
    ;; long single drips for that hand-drawn irregularity
    (dotimes (c cols)
      (setq state (lameserver--xorshift state))
      (setq cur (max 0 (min 3 (+ cur (- (mod state 3) 1)))))
      (when (zerop (mod state 17)) (setq cur 3))
      (aset heights c cur))
    ;; row 0 is the solid mass; rows 1..3 are the fading hangers
    (dotimes (r 4)
      (let ((line (make-string cols ?\s t)))    ; multibyte: cells are blocks
        (dotimes (c cols)
          (let ((h (aref heights c)))
            (aset line c
                  (cond ((= r 0) ?█)
                        ((< r h) (aref "·▓▒░" r))     ; mid-hanger
                        ((= r h) (aref "·░░·" r))     ; the tip
                        (t ?\s)))))
        (push (lameserver--escape line) rows)))
    (format "<pre class=\"drip\" aria-hidden=\"true\">%s</pre>"
            (string-join (nreverse rows) "\n"))))

;;;; ---------------------------------------------------------------- phile head

(defun lameserver--issue-bar (entry)
  "The newsletter issue bar: ▌ phile 0xNN │ ... │ date ▐, plus a creds line."
  (let ((date (if (plist-get entry :time)
                  (format-time-string "%B %Y" (plist-get entry :time))
                "undated")))
    (concat
     "<div class=\"issue\" aria-hidden=\"false\">"
     (format "<span class=\"i-cell\">phile %s</span>" (plist-get entry :phile-hex))
     "<span class=\"i-cell i-mid\">an official lameserver public transmission</span>"
     (format "<span class=\"i-cell\">%s</span>" (lameserver--escape date))
     "</div>"
     "<div class=\"issue-sub\">"
     (mapconcat (lambda (tag)
                  (format "<a class=\"tag\" href=\"/category/%s/\">[%s]</a> "
                          (lameserver--slugify tag) (lameserver--escape tag)))
                (plist-get entry :tags) "")
     (format "· %d min read · " (lameserver--reading-time (plist-get entry :words)))
     (if-let* ((sig (plist-get entry :sig)))
         (format (concat "sig <a class=\"sig ok\" href=\"source.org.asc\" "
                         "title=\"gpg --verify source.org.asc source.org\">"
                         "&#10003; 0x%s</a> <a class=\"sig ok\" href=\"/pubkey.asc\">[pubkey]</a>")
                 (substring sig -16))
       "<span class=\"sig none\">sig: none</span>")
     "</div>")))

(defun lameserver--phile-head (entry)
  "Masthead for a phile, ACiD-newsletter style: quote, logo, issue bar."
  (let ((title (plist-get entry :title))
        (desc (plist-get entry :description)))
    (concat
     (format "<header class=\"phile-head hue-%s\">" (lameserver--hue entry))
     (format "<h1 class=\"vh\">%s</h1>" (lameserver--escape title))
     (lameserver--block-logo title (lameserver--hue entry))
     (if (string-blank-p (or desc ""))
         ""
       (format "<div class=\"pre-quote\">&#8216;%s&#8217;</div>"
               (lameserver--escape desc)))
     (lameserver--issue-bar entry)
     (format "<div class=\"sec-drip\">%s</div>" (lameserver--drip title))
     "</header>")))

(defvar lameserver--section-index 0
  "Counts level-1 sections within one phile, to alternate logo side.")

(defun lameserver--html-headline (headline contents info)
  "Top-level org sections open with their name drawn big in lameblock,
floated to alternating sides so the body text wraps around it — no box,
newsletter style."
  (let ((out (org-html-headline headline contents info)))
    (if (/= 1 (org-element-property :level headline))
        out
      (let* ((raw (replace-regexp-in-string
                   "[*/=~+_]" "" (or (org-element-property :raw-value headline) "")))
             (side (if (cl-oddp (cl-incf lameserver--section-index)) "left" "right"))
             (logo (lameserver--block-logo raw nil 30)))
        (format "<section class=\"phile-sec float-%s\">%s%s</section>"
                side logo out)))))

;;;; ---------------------------------------------------------------- ANSI art

(defun lameserver--sgr-parse (ansi)
  "Parse chafa ANSI output into a list of (CHAR FG BG), FG/BG \"r;g;b\" or nil."
  (let ((pos 0) (len (length ansi)) (fg nil) (bg nil) (cells '()))
    (while (< pos len)
      (let ((ch (aref ansi pos)))
        (cond
         ;; CSI sequence: ESC [ params final-byte
         ((and (= ch ?\e) (< (1+ pos) len) (= (aref ansi (1+ pos)) ?\[))
          (let ((end (+ pos 2)))
            (while (and (< end len) (not (<= ?@ (aref ansi end) ?~)))
              (setq end (1+ end)))
            (when (and (< end len) (= (aref ansi end) ?m))
              (let ((params (split-string (substring ansi (+ pos 2) end) ";")))
                (while params
                  (pcase (pop params)
                    ((or "0" "") (setq fg nil bg nil))
                    ("39" (setq fg nil))
                    ("49" (setq bg nil))
                    ("38" (when (equal (car params) "2")
                            (pop params)
                            (setq fg (string-join (list (pop params) (pop params) (pop params)) ";"))))
                    ("48" (when (equal (car params) "2")
                            (pop params)
                            (setq bg (string-join (list (pop params) (pop params) (pop params)) ";"))))
                    (_ nil)))))
            (setq pos (1+ end))))
         ((= ch ?\n) (push (list ?\n nil nil) cells) (setq pos (1+ pos)))
         ((= ch ?\r) (setq pos (1+ pos)))
         (t (push (list ch fg bg) cells) (setq pos (1+ pos))))))
    (nreverse cells)))

(defun lameserver--ansi->html (ansi id font-class)
  "Convert ANSI escapes to an HTML fragment: scoped <style> + <pre>.
Adjacent cells with identical style are merged into one span; colors are
deduplicated into per-image classes to keep the output small."
  (let ((classes (make-hash-table :test 'equal))
        (order '())
        (out '())
        (run '())
        (cur 'none))
    (cl-flet ((esc (c) (pcase c (?& "&amp;") (?< "&lt;") (?> "&gt;")
                         (_ (char-to-string c))))
              (flush ()
                (when run
                  (let ((text (apply #'concat (nreverse run))))
                    (push (if (equal cur '(nil . nil))
                              text
                            (let ((cls (or (gethash cur classes)
                                           (let ((c (format "c%d" (hash-table-count classes))))
                                             (puthash cur c classes)
                                             (push (cons c cur) order)
                                             c))))
                              (format "<span class=\"%s\">%s</span>" cls text)))
                          out))
                  (setq run '()))))
      (dolist (cell (lameserver--sgr-parse ansi))
        (pcase-let ((`(,ch ,fg ,bg) cell))
          (if (= ch ?\n)
              (progn (flush) (setq cur 'none) (push "\n" out))
            (let ((style (cons fg bg)))
              (unless (equal style cur) (flush) (setq cur style))
              (push (esc ch) run)))))
      (flush))
    (let ((css (mapconcat
                (lambda (c)
                  (pcase-let ((`(,name . (,fg . ,bg)) c))
                    ;; chafa params are "r;g;b" — CSS wants commas
                    (format "#%s .%s{%s%s}" id name
                            (if fg (format "color:rgb(%s);"
                                           (subst-char-in-string ?\; ?, fg))
                              "")
                            (if bg (format "background:rgb(%s);"
                                           (subst-char-in-string ?\; ?, bg))
                              ""))))
                (nreverse order) ""))
          (body (string-trim-right (apply #'concat (nreverse out)))))
      (format "<style>%s</style><pre class=\"ansi-art %s\" id=\"%s\">%s</pre>"
              css font-class id body))))

(defun lameserver--chafa (path size symbols)
  "Run chafa on PATH; return raw ANSI string or nil.
Braille gets fg-only dithered output — dot density carries the image;
per-cell backgrounds would wash the dots out on smooth gradients."
  (when-let* ((chafa (lameserver--tool "chafa")))
    (apply #'lameserver--run chafa
           (append (list "--format" "symbols"
                         "--colors" "full"
                         "--symbols" symbols
                         "--size" size)
                   (when (string-match-p "braille" symbols)
                     (list "--fg-only" "--dither" "diffusion"))
                   (list (expand-file-name path))))))

(defun lameserver--ansi-render (path id &optional size symbols)
  "Cached chafa+HTML conversion of image PATH.  Returns HTML or nil."
  (let* ((size (or size (format "%dx999" lameserver--ansi-width)))
         (symbols (or symbols "half+space"))
         (font-class (cond ((string-match-p "braille" symbols) "ansi-braille")
                           ((string-match-p "quad\\|sextant\\|all" symbols) "ansi-argon")
                           (t "ansi-vga")))
         (mtime (file-attribute-modification-time (file-attributes path)))
         (key (secure-hash 'sha1 (format "%s|%s|%s|%s|%s" (expand-file-name path)
                                         (float-time mtime) size symbols
                                         lameserver--converter-version)))
         (cache (lameserver--cache "ansi" (concat key ".html"))))
    (if (file-exists-p cache)
        (let ((html (with-temp-buffer (insert-file-contents cache) (buffer-string))))
          ;; the cached fragment embeds an id; re-target it for this use site
          (replace-regexp-in-string "__ID__" id html t t))
      (when-let* ((ansi (lameserver--chafa path size symbols)))
        (let ((html (lameserver--ansi->html ansi "__ID__" font-class)))
          (when (> (length html) lameserver--ansi-warn-bytes)
            (lameserver--log "lameserver: WARNING %s renders to %dKB of ANSI html"
                             (file-name-nondirectory path) (/ (length html) 1024)))
          (with-temp-file cache (insert html))
          (replace-regexp-in-string "__ID__" id html t t))))))

(defun lameserver--emblem (seed-string &optional w h)
  "Deterministic ANSI block-art emblem for posts without images."
  (let* ((w (or w 22)) (h (or h 11))
         (half (/ (+ w 1) 2))
         (state (string-to-number
                 (substring (secure-hash 'sha1 seed-string) 0 8) 16))
         (chars " ░▒▓█▀▄")
         (rows '()))
    (when (zerop state) (setq state 305419896))
    (dotimes (_y h)
      (let ((cells '()))
        (dotimes (_x half)
          (setq state (lameserver--xorshift state))
          (let* ((c (aref chars (mod state (length chars))))
                 (cls (aref lameserver--emblem-classes
                            (mod (ash state -8) (length lameserver--emblem-classes)))))
            (push (cons c (if (eq c ?\s) nil cls)) cells)))
        ;; mirror for that classic logo symmetry
        (let ((left (reverse cells)))
          (push (append left (cdr (reverse left))) rows))))
    (let ((body
           (mapconcat
            (lambda (row)
              (mapconcat
               (lambda (cell)
                 (if (cdr cell)
                     (format "<span class=\"%s\">%c</span>" (cdr cell) (car cell))
                   (char-to-string (car cell))))
               row ""))
            (nreverse rows) "\n")))
      (format "<pre class=\"ansi-art ansi-vga emblem\" aria-hidden=\"true\">%s</pre>" body))))

;;;; ---------------------------------------------------------------- media urls

(defun lameserver--media-url (path org-file)
  "Site-absolute URL for media PATH referenced from ORG-FILE, or nil."
  (let* ((abs (expand-file-name path (file-name-directory org-file)))
         (media-root (file-truename (lameserver--path "org/media"))))
    (when (string-prefix-p media-root (file-truename abs))
      (concat "/media/" (file-relative-name (file-truename abs) media-root)))))

;;;; ---------------------------------------------------------------- export backend

(defvar lameserver--image-counter 0)

(defun lameserver--attr-plist (element)
  "Read #+ATTR_LAMESERVER plist attached to ELEMENT's paragraph."
  (when-let* ((parent (org-element-lineage element '(paragraph))))
    (org-export-read-attribute :attr_lameserver parent)))

(defun lameserver--image-figure (path org-file attrs)
  "Image as pure ANSI text.  The source raster is a build input only —
nothing but text ships."
  (let* ((width (min lameserver--ansi-max-width
                     (max 20 (or (and (plist-get attrs :width)
                                      (string-to-number (plist-get attrs :width)))
                                 lameserver--ansi-width))))
         (symbols (or (plist-get attrs :symbols) "half+space"))
         (id (format "ansi%d" (cl-incf lameserver--image-counter)))
         (alt (or (plist-get attrs :alt) (file-name-base path)))
         (ansi (lameserver--ansi-render
                (expand-file-name path (file-name-directory org-file))
                id (format "%dx999" width)
                (pcase symbols
                  ("braille" "braille")
                  ("quad" "quad+half+space")
                  (_ symbols)))))
    (if (not ansi)
        (progn
          (lameserver--log "lameserver: WARNING no ANSI renderer — %s dropped" path)
          (format "<pre class=\"ansi-art ansi-missing\">[ image: %s — no renderer at build time ]</pre>"
                  (lameserver--escape (file-name-nondirectory path))))
      (format "<figure class=\"ansi-img\" role=\"img\" aria-label=\"%s\">%s</figure>"
              (lameserver--escape alt) ansi))))

(defun lameserver--av-html (path org-file)
  "Audio/video element inside box-drawing chrome."
  (let ((url (or (lameserver--media-url path org-file) path))
        (ext (downcase (or (file-name-extension path) ""))))
    (format "<div class=\"ansi-frame\">%s</div>"
            (if (member ext '("mp3" "ogg" "flac" "wav"))
                (format "<audio controls preload=\"metadata\" src=\"%s\"></audio>" url)
              (format "<video controls preload=\"metadata\" src=\"%s\"></video>" url)))))

(defun lameserver--html-link (link desc info)
  "Intercept media links; delegate everything else to ox-html."
  (let* ((type (org-element-property :type link))
         (path (org-element-property :path link))
         (ext (downcase (or (file-name-extension (or path "")) "")))
         (org-file (plist-get info :input-file)))
    (cond
     ;; images always become ANSI text — described or not, nothing raster ships
     ((and (string= type "file")
           (member ext '("png" "jpg" "jpeg" "gif" "webp")))
      (lameserver--image-figure path org-file
                                (append (and desc (list :alt desc))
                                        (lameserver--attr-plist link))))
     ((and (string= type "file")
           (member ext '("mp4" "webm" "mp3" "ogg" "flac" "wav")))
      (lameserver--av-html path org-file))
     ;; rewrite plain file links into org/media to their published URL
     ((and (string= type "file") (lameserver--media-url path org-file))
      (format "<a href=\"%s\">%s</a>"
              (lameserver--media-url path org-file) (or desc path)))
     (t (org-html-link link desc info)))))

;;;; ---------------------------------------------------------------- page chrome

(defconst lameserver--menu
  '(("board" . "/board/") ("about" . "/about/") ("rss" . "/feed.xml"))
  "Site menu; the first letter of each label is its live hotkey.")

(defun lameserver--menu-html (active &optional loc)
  "Menu bar; LOC is the BBS-style \"current area\" field, right-aligned."
  (concat
   "<nav class=\"menu\" aria-label=\"site\">"
   (mapconcat
    (lambda (item)
      (let* ((label (car item)) (href (cdr item))
             (hot (substring label 0 1)) (rest (substring label 1)))
        (format "<a href=\"%s\"%s>(<span class=\"hot\">%s</span>)%s</a>"
                href
                (if (equal label active) " class=\"active\"" "")
                hot rest)))
    lameserver--menu " ")
   "<a href=\"/board/#search\">(<span class=\"hot\">/</span>)search</a>"
   (when loc
     (format "<span class=\"menu-loc\" aria-hidden=\"true\">▓▒ %s</span>"
             (lameserver--escape loc)))
   "</nav>"))

(defun lameserver--masthead (right)
  (format (concat "<div class=\"masthead\" aria-hidden=\"true\">"
                  "<span class=\"cap\">░▒▓</span>"
                  "<span class=\"rail\">══[ </span>%s<span class=\"rail\"> ]══</span>"
                  "<span class=\"rail-fill\"></span>"
                  "<span class=\"rail\">══[ </span>%s<span class=\"rail\"> ]══</span>"
                  "<span class=\"cap\">▓▒░</span>"
                  "</div>")
          lameserver--site-name right))

(defun lameserver--footer ()
  (format (concat "<footer class=\"site-footer\">"
                  "<button class=\"foot-rail\" type=\"button\" aria-label=\"hang up\">"
                  "░▒▓█▓▒░ ░▒▓█▓▒░ ░▒▓█▓▒░</button>"
                  "<div class=\"foot-node\" aria-hidden=\"true\">"
                  "<span class=\"chip\">node 1/1</span>"
                  "<span class=\"chip\">38400 8n1</span>"
                  "<span class=\"chip\">ansi</span>"
                  "<span class=\"chip chip-ok\">carrier ok</span>"
                  "</div>"
                  "<p><a href=\"%s\">lameserver.net</a> · last updated %s</p>"
                  "<p class=\"foot-fine\">org-mode → elisp → ANSI · no trackers, no frameworks · "
                  "type set in Monaspace Argon, Px437 IBM VGA (CC BY-SA 4.0 int10h.org), GNU FreeMono</p>"
                  "</footer>")
          lameserver--site-url
          (or lameserver--build-stamp "unknown")))

(defun lameserver--page-shell (&rest args)
  "Full HTML page.  ARGS plist: :title :desc :canonical :masthead-right
:active :loc :body :extra-head :body-script"
  (let ((title (plist-get args :title))
        (desc (or (plist-get args :desc) "lameserver.net — a bulletin board"))
        (canonical (plist-get args :canonical)))
    (concat
     "<!doctype html>\n<html lang=\"en\">\n<head>\n"
     "<meta charset=\"utf-8\">\n"
     "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
     (format "<title>%s</title>\n" (lameserver--escape title))
     (format "<meta name=\"description\" content=\"%s\">\n" (lameserver--escape desc))
     (when canonical
       (format "<link rel=\"canonical\" href=\"%s\">\n" canonical))
     "<link rel=\"alternate\" type=\"application/rss+xml\" title=\"lameserver\" href=\"/feed.xml\">\n"
     "<link rel=\"icon\" href=\"data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'><text y='13' font-size='13' fill='%23ff79c6'>▓</text></svg>\">\n"
     "<link rel=\"stylesheet\" href=\"/assets/css/site.css\">\n"
     "<link rel=\"stylesheet\" href=\"/assets/css/dracula.css\">\n"
     (or (plist-get args :extra-head) "")
     "</head>\n<body>\n"
     "<header class=\"site-header\">"
     "<a class=\"skip\" href=\"#content\">skip to content</a>"
     "<!-- the space above can be used to advertise your lame BBS if you so desire. . .  - stc/acid, 1995 -->"
     "<div id=\"banner\" role=\"img\" aria-label=\"lameserver\">"
     (lameserver--block-logo "lameserver" nil 90)
     "</div>"
     (lameserver--masthead (or (plist-get args :masthead-right) "est. 2026"))
     (lameserver--menu-html (plist-get args :active) (plist-get args :loc))
     "</header>\n"
     "<main id=\"content\">\n"
     (plist-get args :body)
     "\n</main>\n"
     (lameserver--footer)
     "<script src=\"/assets/js/header.js\" defer></script>\n"
     (or (plist-get args :body-script) "")
     "</body>\n</html>\n")))

;;;; ---------------------------------------------------------------- post template

(defun lameserver--reading-time (words)
  (max 1 (round (/ (or words 0) 220.0))))

(defun lameserver--share-html (entry)
  (let* ((url (plist-get entry :url))
         (eurl (url-hexify-string url))
         (etitle (url-hexify-string (plist-get entry :title))))
    (concat
     "<section class=\"share\" aria-label=\"share\">"
     (format "<div class=\"share-rail\" aria-hidden=\"true\">.oO( share this phile )Oo.</div>")
     "<div class=\"share-links\">"
     (format "<a rel=\"noopener\" target=\"_blank\" href=\"https://twitter.com/intent/tweet?url=%s&amp;text=%s\">[x]</a>" eurl etitle)
     (format "<button type=\"button\" class=\"share-fedi\" data-url=\"%s\" data-title=\"%s\">[fedi]</button>"
             (lameserver--escape url) (lameserver--escape (plist-get entry :title)))
     (format "<a rel=\"noopener\" target=\"_blank\" href=\"https://news.ycombinator.com/submitlink?u=%s&amp;t=%s\">[hn]</a>" eurl etitle)
     (format "<a rel=\"noopener\" target=\"_blank\" href=\"https://www.reddit.com/submit?url=%s&amp;title=%s\">[reddit]</a>" eurl etitle)
     (format "<a rel=\"noopener\" target=\"_blank\" href=\"https://lobste.rs/stories/new?url=%s&amp;title=%s\">[lobsters]</a>" eurl etitle)
     (format "<button type=\"button\" class=\"share-copy\" data-url=\"%s\">[copy url]</button>"
             (lameserver--escape url))
     "</div></section>")))

(defun lameserver--neighbor-rail (entry)
  (let* ((posts (lameserver--published))
         (pos (cl-position entry posts :test #'eq))
         (next (and pos (> pos 0) (nth (1- pos) posts)))          ; newer
         (prev (and pos (nth (1+ pos) posts))))                   ; older
    (concat
     "<nav class=\"phile-rail\" aria-label=\"neighboring philes\">"
     (if prev
         (format "<a id=\"prev-phile\" href=\"/phile/%s/\">&#8592; %s %s</a>"
                 (plist-get prev :phile-hex) (plist-get prev :phile-hex)
                 (lameserver--escape (plist-get prev :title)))
       "<span class=\"dim\">&#8592; older: none</span>")
     "<a href=\"/board/\">[board]</a>"
     (if next
         (format "<a id=\"next-phile\" href=\"/phile/%s/\">%s %s &#8594;</a>"
                 (plist-get next :phile-hex) (plist-get next :phile-hex)
                 (lameserver--escape (plist-get next :title)))
       "<span class=\"dim\">newer: none &#8594;</span>")
     "</nav>")))

(defun lameserver--html-template (contents info)
  "Full page for a post (or page) exported through the derived backend."
  (let* ((file (plist-get info :input-file))
         (entry (lameserver--manifest-entry file)))
    (if (null entry)
        ;; a plain page (about etc.): lighter chrome, named in the menu bar
        (let ((title (org-export-data (plist-get info :title) info)))
          (lameserver--page-shell
           :title (format "%s · lameserver" title)
           :active (lameserver--slugify title)
           :loc title
           :body (concat (format "<h1 class=\"vh\">%s</h1>" (lameserver--escape title))
                         "<article class=\"phile-body\">" contents "</article>")
           :body-script "<script src=\"/assets/js/phile.js\" defer></script>"))
      (let ((title (plist-get entry :title))
            (divider (lameserver--divider entry)))
        (lameserver--page-shell
         :title (format "%s · lameserver" title)
         :desc (plist-get entry :description)
         :canonical (plist-get entry :url)
         :masthead-right (format "phile %s of %s"
                                 (plist-get entry :phile-hex)
                                 (lameserver--phile-hex
                                  (plist-get (car (lameserver--published)) :phile)))
         :active "board"
         :loc (format "board › %s" (plist-get entry :phile-hex))
         :body (concat
                (lameserver--phile-head entry)
                "<article class=\"phile-body\">" contents "</article>"
                (format "<div class=\"divider hue-%s\" aria-hidden=\"true\">%s</div>"
                        (lameserver--hue entry) divider)
                (lameserver--share-html entry)
                (lameserver--neighbor-rail entry))
         :body-script "<script src=\"/assets/js/phile.js\" defer></script>")))))

(org-export-define-derived-backend 'lameserver-html 'html
  :translate-alist '((template . lameserver--html-template)
                     (link . lameserver--html-link)
                     (headline . lameserver--html-headline))
  :options-alist '((:phile "PHILE" nil nil t)
                   (:thumb "THUMB" nil nil t)
                   (:draft "DRAFT" nil nil t)))

;;;; ---------------------------------------------------------------- exporting

(defconst lameserver--export-plist
  '(:section-numbers t
    :with-toc nil
    :with-author nil
    :with-email nil
    :with-creator nil
    :with-date nil
    :with-sub-superscript {}
    :html-doctype "html5"
    :html-html5-fancy t))

(defmacro lameserver--with-export-env (&rest body)
  "Run BODY with export options safely scoped (daemon hygiene)."
  `(let ((org-export-use-babel nil)
         (org-confirm-babel-evaluate t)
         (org-html-htmlize-output-type
          (if (require 'htmlize nil t) 'css nil))
         (org-export-with-broken-links 'mark)
         (coding-system-for-write 'utf-8)
         (make-backup-files nil)
         (system-time-locale "C")
         ;; htmlize fontifies src blocks in temp buffers; a daemon's UI mode
         ;; hooks (indent-bars etc.) break or pollute that — export wants
         ;; pure font-lock, so run every mode bare
         (prog-mode-hook nil)
         (text-mode-hook nil)
         (org-mode-hook nil))
     ,@body))

(defun lameserver--export-file (file outfile)
  "Export org FILE to OUTFILE through the lameserver backend."
  (make-directory (file-name-directory outfile) t)
  (let ((visiting (find-buffer-visiting file))
        (lameserver--section-index 0))     ; alternation restarts each phile
    (with-current-buffer (or visiting (find-file-noselect file))
      (unwind-protect
          (org-export-to-file 'lameserver-html outfile
            nil nil nil nil lameserver--export-plist)
        (unless visiting (kill-buffer (current-buffer)))))))

(defun lameserver--post-plaintext (file)
  "Plaintext body of FILE for the search index (truncated)."
  (let ((visiting (find-buffer-visiting file)))
    (with-current-buffer (or visiting (find-file-noselect file))
      (unwind-protect
          (let ((txt (org-export-as 'ascii nil nil t
                                    '(:with-toc nil :section-numbers nil))))
            (substring txt 0 (min 2000 (length txt))))
        (unless visiting (kill-buffer (current-buffer)))))))

;;;; ---------------------------------------------------------------- signing

(defun lameserver--sign-posts ()
  "Detach-sign every published phile's org source into its output dir.
Each entry gains :sig (the signing key fingerprint) on success.  Readers
verify with: gpg --verify source.org.asc source.org"
  (if (not (lameserver--tool "gpg"))
      (lameserver--log "lameserver: gpg not found — philes ship unsigned")
    (dolist (e (lameserver--published))
      (let* ((src (plist-get e :file))
             (dir (lameserver--docs "phile" (plist-get e :phile-hex)))
             (dst (expand-file-name "source.org" dir))
             (asc (concat dst ".asc")))
        (make-directory dir t)
        (copy-file src dst t)
        (when (or (not (file-exists-p asc))
                  (file-newer-than-file-p src asc))
          (apply #'lameserver--run "gpg"
                 (append '("--batch" "--yes" "--armor" "--detach-sign")
                         (and lameserver--gpg-key
                              (list "--local-user" lameserver--gpg-key))
                         (list "--output" asc dst))))
        (when (file-exists-p asc)
          (when-let* ((v (lameserver--run "gpg" "--status-fd" "1"
                                          "--verify" asc dst)))
            (when (string-match "VALIDSIG \\([0-9A-F]+\\)" v)
              (plist-put e :sig (match-string 1 v)))))
        (unless (plist-get e :sig)
          (lameserver--log "lameserver: WARNING %s is unsigned"
                           (plist-get e :phile-hex)))))
    ;; ship the public key so signatures are verifiable
    (when-let* ((entry (cl-find-if (lambda (e) (plist-get e :sig))
                                   (lameserver--published)))
                (pub (lameserver--run "gpg" "--armor" "--export"
                                      (plist-get entry :sig))))
      (with-temp-file (lameserver--docs "pubkey.asc") (insert pub)))))

;;;; ---------------------------------------------------------------- thumbs

(defun lameserver--thumb-html (entry)
  "Board-listing thumbnail: #+THUMB, else first image, else emblem."
  (let* ((file (plist-get entry :file))
         (src (or (plist-get entry :thumb) (plist-get entry :first-image)))
         (abs (and src (expand-file-name src (file-name-directory file)))))
    (or (and abs (file-exists-p abs)
             (lameserver--ansi-render
              abs (format "th%s" (plist-get entry :phile-hex))
              lameserver--thumb-size "half+space"))
        (lameserver--emblem (concat (plist-get entry :phile-hex)
                                    (plist-get entry :slug))))))

;;;; ---------------------------------------------------------------- board & categories

(defun lameserver--listing-row (entry)
  "One board entry as a FILE_ID.DIZ-style card: thumb as the logo,
title as the release name, block rules top and bottom."
  (let ((hex (plist-get entry :phile-hex))
        (date (if (plist-get entry :time)
                  (format-time-string "%Y-%m-%d" (plist-get entry :time))
                "undated")))
    (format (concat "<li class=\"row hue-%s\">"
                    "<span class=\"row-hex\" aria-hidden=\"true\">┤ %s ├</span>"
                    "<span class=\"row-thumb\" aria-hidden=\"true\">%s</span>"
                    "<span class=\"row-head\">"
                    "<a class=\"row-link\" href=\"/phile/%s/\">"
                    "<span class=\"row-title\">%s</span></a>%s</span>"
                    "<span class=\"row-desc\">%s</span>"
                    "<span class=\"row-foot\"><span class=\"row-date\">%s</span>"
                    "<span class=\"row-tags\">%s</span></span>"
                    "</li>")
            (lameserver--hue entry)
            hex
            (lameserver--thumb-html entry)
            hex
            (lameserver--escape (plist-get entry :title))
            (if (plist-get entry :sig)
                " <span class=\"sig ok\" title=\"signed\">&#10003;</span>" "")
            (lameserver--escape (plist-get entry :description))
            date
            (mapconcat (lambda (tag)
                         (format "<a class=\"tag\" href=\"/category/%s/\">[%s]</a>"
                                 (lameserver--slugify tag) (lameserver--escape tag)))
                       (plist-get entry :tags) " "))))

(defun lameserver--listing-page (title posts out-dir &optional lead)
  (let ((body
         (concat
          (format "<h1 class=\"vh\">%s</h1>" (lameserver--escape title))
          (or lead "")
          "<div class=\"board-bar\"><label id=\"search\" class=\"search-prompt\">"
          "search&gt; <input type=\"search\" id=\"board-search\" autocomplete=\"off\" "
          "spellcheck=\"false\" aria-label=\"search philes\"></label>"
          "<span class=\"board-hint\" aria-hidden=\"true\">j/k move · enter opens · / search · ? help</span></div>"
          "<ul class=\"board\" id=\"board-list\">"
          (mapconcat #'lameserver--listing-row posts "\n")
          "</ul>")))
    (make-directory out-dir t)
    (with-temp-file (expand-file-name "index.html" out-dir)
      (insert (lameserver--page-shell
               :title (format "%s · lameserver" title)
               :active "board"
               :loc title
               :masthead-right (format "%d philes on file" (length posts))
               :body body
               :body-script "<script src=\"/assets/js/board.js\" defer></script>")))))

(defun lameserver--write-board ()
  (lameserver--listing-page "the board" (lameserver--published)
                            (lameserver--docs "board")))

(defun lameserver--all-tags ()
  (let ((tags '()))
    (dolist (e (lameserver--published))
      (dolist (tag (plist-get e :tags))
        (cl-pushnew tag tags :test #'equal)))
    (sort tags #'string<)))

(defun lameserver--write-categories ()
  (dolist (tag (lameserver--all-tags))
    (let ((posts (cl-remove-if-not
                  (lambda (e) (member tag (plist-get e :tags)))
                  (lameserver--published))))
      (lameserver--listing-page
       (format "category: %s" tag) posts
       (lameserver--docs "category" (lameserver--slugify tag))
       (format "<p class=\"lead\"><a href=\"/board/\">&#8592; all philes</a></p>")))))

;;;; ---------------------------------------------------------------- feed & search

(defun lameserver--rfc822 (time)
  (let ((system-time-locale "C"))
    (format-time-string "%a, %d %b %Y %H:%M:%S %z" (or time (current-time)))))

(defun lameserver--write-feed ()
  (with-temp-file (lameserver--docs "feed.xml")
    (insert "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            "<rss version=\"2.0\" xmlns:atom=\"http://www.w3.org/2005/Atom\">\n<channel>\n"
            "<title>lameserver</title>\n"
            (format "<link>%s/</link>\n" lameserver--site-url)
            "<description>philes from the board at lameserver.net</description>\n"
            (format "<atom:link href=\"%s/feed.xml\" rel=\"self\" type=\"application/rss+xml\"/>\n"
                    lameserver--site-url)
            (format "<lastBuildDate>%s</lastBuildDate>\n" (lameserver--rfc822 nil)))
    (dolist (e (lameserver--published))
      (insert "<item>\n"
              (format "<title>%s</title>\n" (lameserver--escape (plist-get e :title)))
              (format "<link>%s</link>\n" (plist-get e :url))
              (format "<guid isPermaLink=\"true\">%s</guid>\n" (plist-get e :url))
              (format "<pubDate>%s</pubDate>\n" (lameserver--rfc822 (plist-get e :time)))
              (format "<description>%s</description>\n"
                      (lameserver--escape (plist-get e :description)))
              "</item>\n"))
    (insert "</channel>\n</rss>\n")))

(defun lameserver--write-search-json ()
  (let ((items
         (mapcar
          (lambda (e)
            `((phile . ,(plist-get e :phile-hex))
              (title . ,(plist-get e :title))
              (url . ,(format "/phile/%s/" (plist-get e :phile-hex)))
              (date . ,(if (plist-get e :time)
                           (format-time-string "%Y-%m-%d" (plist-get e :time))
                         ""))
              (tags . ,(vconcat (or (plist-get e :tags) [])))
              (description . ,(plist-get e :description))
              (text . ,(or (ignore-errors
                             (lameserver--post-plaintext (plist-get e :file)))
                           ""))))
          (lameserver--published))))
    (with-temp-file (lameserver--docs "search.json")
      (insert (json-serialize (vconcat items))))))

;;;; ---------------------------------------------------------------- static & prune

(defun lameserver--copy-tree (src dst)
  (when (file-directory-p dst) (delete-directory dst t))
  (when (file-directory-p src) (copy-directory src dst t t t)))

(defun lameserver--write-static ()
  ;; assets (minus static/) -> docs/assets.  Media: only audio/video ship —
  ;; images exist solely as build inputs for the ANSI conversion.
  (let ((tmp-static (lameserver--path "assets/static")))
    (lameserver--copy-tree (lameserver--path "assets") (lameserver--docs "assets"))
    (delete-directory (lameserver--docs "assets/static") t)
    (lameserver--copy-tree (lameserver--path "org/media") (lameserver--docs "media"))
    (dolist (img (ignore-errors
                   (directory-files-recursively
                    (lameserver--docs "media")
                    "\\.\\(?:png\\|jpe?g\\|gif\\|webp\\|svg\\)\\'")))
      (delete-file img))
    ;; splash + CNAME + .nojekyll at the docs root
    (copy-file (expand-file-name "index.html" tmp-static)
               (lameserver--docs "index.html") t)
    (copy-file (expand-file-name "CNAME" tmp-static)
               (lameserver--docs "CNAME") t)
    (with-temp-file (lameserver--docs ".nojekyll"))))

(defun lameserver--prune ()
  "Delete published dirs whose source is gone or re-drafted."
  (let ((live-philes (mapcar (lambda (e) (plist-get e :phile-hex))
                             (lameserver--published)))
        (live-tags (mapcar #'lameserver--slugify (lameserver--all-tags))))
    (dolist (dir (ignore-errors
                   (directory-files (lameserver--docs "phile") t "\\`0x")))
      (unless (member (file-name-nondirectory dir) live-philes)
        (lameserver--log "lameserver: pruning %s" dir)
        (delete-directory dir t)))
    (dolist (dir (ignore-errors
                   (directory-files (lameserver--docs "category") t "\\`[^.]")))
      (unless (member (file-name-nondirectory dir) live-tags)
        (lameserver--log "lameserver: pruning %s" dir)
        (delete-directory dir t)))))

;;;; ---------------------------------------------------------------- orchestrator

(defun lameserver-publish ()
  "Build the whole site into docs/."
  (interactive)
  (let ((t0 (current-time)))
    (setq lameserver--build-stamp
          (let ((system-time-locale "C"))
            (format-time-string "%Y-%m-%d %H:%M UTC" nil t))
          lameserver--image-counter 0)
    (lameserver--scan-posts)
    (lameserver--with-export-env
     (unless (lameserver--tool "chafa")
       (lameserver--log "lameserver: chafa not found — images ship as plain <img>"))
     (unless (featurep 'htmlize)
       (lameserver--log "lameserver: htmlize not found — code blocks unfontified"))
     (lameserver--write-static)
     (lameserver--sign-posts)
     (dolist (e (lameserver--published))
       (lameserver--export-file
        (plist-get e :file)
        (lameserver--docs "phile" (plist-get e :phile-hex) "index.html")))
     (dolist (page (ignore-errors
                     (directory-files (lameserver--path "org/pages") t "\\.org\\'")))
       (lameserver--export-file
        page (lameserver--docs (file-name-base page) "index.html")))
     (lameserver--write-board)
     (lameserver--write-categories)
     (lameserver--write-feed)
     (lameserver--write-search-json)
     (lameserver--prune))
    (lameserver--log "lameserver: built %d philes in %.1fs"
                     (length (lameserver--published))
                     (float-time (time-subtract (current-time) t0)))))

(defun lameserver-publish-batch ()
  "Batch entry point: build and exit non-zero on error."
  (lameserver-publish))

(defun lameserver-deploy ()
  "Build, commit, and push."
  (interactive)
  (lameserver-publish)
  (let ((default-directory lameserver--root))
    (if (string-blank-p (or (lameserver--run "git" "status" "--porcelain") ""))
        (lameserver--log "lameserver: nothing to deploy — tree is clean")
      (or (and (lameserver--run "git" "add" "-A" "--" "org" "assets" "docs"
                                "publish.el" ".dir-locals.el" ".gitignore")
               (lameserver--run "git" "commit" "-m"
                                (format "publish: %s" lameserver--build-stamp))
               (lameserver--run "git" "push")
               (prog1 t
                 (lameserver--log "lameserver: deployed → %s/board/" lameserver--site-url)))
          (user-error "lameserver: deploy failed — see *lameserver-log*")))))

(defun lameserver-clean ()
  "Delete docs/ and .cache/ after confirming."
  (interactive)
  (when (or noninteractive
            (yes-or-no-p "Delete docs/ and .cache/ entirely? "))
    (dolist (d (list (lameserver--docs) (lameserver--path ".cache")))
      (when (file-directory-p d) (delete-directory d t)))
    (lameserver--log "lameserver: clean")))

(provide 'lameserver-publish)
;;; publish.el ends here
