;;; publish.el --- build lameserver.net from org sources  -*- lexical-binding: t; -*-

;; The whole static-site build for https://lameserver.net — an ANSI/BBS-style
;; blog written in org-mode.  Everything under docs/ is generated by this file:
;;
;;   org/posts/NNNN-slug.org  ->  docs/phile/0xNN/index.html
;;   org/pages/about.org      ->  docs/about/index.html
;;   org/media/               ->  docs/media/
;;   assets/                  ->  docs/assets/  (static/ copied to docs/ root)
;;   + board listing, category pages, feed.xml, search.json
;;
;; Images in posts are converted to colored ANSI art at build time (chafa),
;; parsed from SGR escapes into HTML by pure elisp.  Post titles are FIGlet.
;; Missing tools degrade gracefully: no chafa -> plain <img>, no figlet ->
;; styled heading, no htmlize -> unfontified code blocks.
;;
;; Entry points:
;;   M-x lameserver-publish        build docs/
;;   M-x lameserver-deploy         build + git add/commit/push
;;   M-x lameserver-clean          wipe docs/ + .cache/
;;   emacs --batch -l publish.el -f lameserver-publish-batch

;;; Code:

(require 'cl-lib)
(require 'ox)
(require 'ox-html)
(require 'ox-ascii)
(require 'xml)
(require 'url-util)
(require 'subr-x)

(defconst lameserver--root
  (file-name-directory (or load-file-name buffer-file-name))
  "Repository root, derived from this file's location.")

(defconst lameserver--site-url "https://lameserver.net")
(defconst lameserver--site-name "lameserver")
(defconst lameserver--converter-version "v2"
  "Bump to invalidate every cached ANSI/figlet conversion.")

(defvar lameserver--gpg-key "44DF29BCAD9943D8"
  "Key philes are signed with (grim@samhain.su).  Nil = gpg default key.")

(defconst lameserver--ansi-width 76 "Default chafa width in cells.")
(defconst lameserver--ansi-max-width 120)
(defconst lameserver--thumb-size "24x12")
(defconst lameserver--ansi-warn-bytes 300000)

(defconst lameserver--dividers
  ["▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▓▓▒▒░░ ∙ ·"
   "▀▄▄▀▀▄▄▄▀▀▀▄▄ ▄▄▄ ▄▄ ▄ ∙ ·"
   "░▒▓██▓▒░▒▓███▓▒░ ·∙ ·\n   ▀▀▀▀▀▀▀▓▒░ ·"
   "∙ ·░░▒▒▓▓████▓▓▒▒░░· ∙"
   "▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓\n ▀▓▒░  ▀▓▒░   ▀▓▒░  ·"
   "░▒░▓█▓░▒░ ▒█▓ ░▓ ▒ ░ ·"
   "· ∙ ░ ▒ ▓ █ ▓ ▒ ░ ∙ ·"]
  "Per-post divider strings, artscene style (multi-line via \\n);
one is picked deterministically per phile.")

(defconst lameserver--emblem-classes
  ["dc-cyan" "dc-green" "dc-orange" "dc-pink" "dc-purple" "dc-red" "dc-yellow"]
  "Dracula color classes used by procedural emblems (defined in site.css).")

(defvar lameserver--manifest nil
  "List of post plists, sorted by phile number descending (newest first).")

(defvar lameserver--build-stamp nil
  "Human-readable stamp for the footer, set once per build.")

;;;; ---------------------------------------------------------------- paths

(defun lameserver--path (&rest parts)
  (expand-file-name (string-join parts "/") lameserver--root))

(defun lameserver--docs (&rest parts)
  (apply #'lameserver--path "docs" parts))

(defun lameserver--cache (&rest parts)
  (let ((f (apply #'lameserver--path ".cache" parts)))
    (make-directory (file-name-directory f) t)
    f))

;;;; ---------------------------------------------------------------- logging

(defun lameserver--log (fmt &rest args)
  (let ((msg (apply #'format fmt args)))
    (with-current-buffer (get-buffer-create "*lameserver-log*")
      (goto-char (point-max))
      (insert msg "\n"))
    (if noninteractive (princ (concat msg "\n")) (message "%s" msg))))

;;;; ---------------------------------------------------------------- tools

(defvar lameserver--tools (make-hash-table :test 'equal))

(defun lameserver--tool (name)
  "Return the executable for NAME, nil if absent (memoized per session)."
  (let ((hit (gethash name lameserver--tools 'miss)))
    (if (eq hit 'miss)
        (puthash name (executable-find name) lameserver--tools)
      hit)))

(defun lameserver--run (program &rest args)
  "Run PROGRAM with ARGS; return stdout string, or nil on failure (logged)."
  (with-temp-buffer
    (let ((status (apply #'call-process program nil t nil args)))
      (if (and (numberp status) (zerop status))
          (buffer-string)
        (lameserver--log "lameserver: %s %s failed (%s): %s"
                         program (string-join args " ") status
                         (string-trim (buffer-string)))
        nil))))

;;;; ---------------------------------------------------------------- misc

(defun lameserver--slugify (s)
  (string-trim (replace-regexp-in-string
                "[^a-z0-9]+" "-" (downcase s)) "-+" "-+"))

(defun lameserver--escape (s)
  (xml-escape-string (or s "")))

(defun lameserver--phile-hex (n) (format "0x%02x" n))

(defun lameserver--seed (string bits)
  "Deterministic integer in [0,BITS) from STRING."
  (mod (string-to-number (substring (secure-hash 'sha1 string) 0 8) 16) bits))

(defun lameserver--xorshift (state)
  "One xorshift32 step; returns new 32-bit STATE."
  (let ((s state))
    (setq s (logand #xffffffff (logxor s (ash s 13))))
    (setq s (logand #xffffffff (logxor s (ash s -17))))
    (setq s (logand #xffffffff (logxor s (ash s 5))))
    (if (zerop s) 88172645463325252 s)))

;;;; ---------------------------------------------------------------- manifest

(defconst lameserver--kw-re
  "^#\\+\\(TITLE\\|DATE\\|FILETAGS\\|PHILE\\|THUMB\\|DESCRIPTION\\|DRAFT\\):[ \t]*\\(.*?\\)[ \t]*$")

(defun lameserver--read-keywords (file)
  "Scan FILE's preamble for keywords; also record first image and word count."
  (with-temp-buffer
    (insert-file-contents file)
    (let ((kw '()) first-image)
      (save-excursion
        (let ((case-fold-search t))
          (while (re-search-forward lameserver--kw-re nil t)
            (push (cons (upcase (match-string 1)) (match-string 2)) kw))))
      (save-excursion
        (when (re-search-forward
               "\\[\\[file:\\([^]]+\\.\\(?:png\\|jpe?g\\|gif\\|webp\\)\\)\\]"
               nil t)
          (setq first-image (match-string 1))))
      (let ((words (count-words (point-min) (point-max))))
        (list :keywords kw :first-image first-image :words words)))))

(defun lameserver--scan-posts ()
  "Build `lameserver--manifest' from org/posts/*.org."
  (let ((entries '()))
    (dolist (file (directory-files (lameserver--path "org/posts") t "\\.org\\'"))
      (let* ((scan (lameserver--read-keywords file))
             (kw (plist-get scan :keywords))
             (get (lambda (k) (cdr (assoc k kw))))
             (title (or (funcall get "TITLE")
                        (file-name-base file)))
             (phile-raw (funcall get "PHILE"))
             (phile (and phile-raw (string-to-number
                                    (string-remove-prefix "0x" phile-raw) 16)))
             (date (funcall get "DATE"))
             (tags (and (funcall get "FILETAGS")
                        (split-string (funcall get "FILETAGS") ":" t "[ \t]+")))
             ;; #+DRAFT: t marks a draft; absent or nil/no/false/0 publishes
             (draft (let ((v (funcall get "DRAFT")))
                      (and v (not (member (downcase v)
                                          '("" "nil" "no" "false" "0")))))))
        (unless phile
          (error "lameserver: %s has no #+PHILE: keyword" file))
        (push (list :file file
                    :phile phile
                    :phile-hex (lameserver--phile-hex phile)
                    :slug (lameserver--slugify title)
                    :title title
                    :date date
                    :time (and date (ignore-errors (org-time-string-to-time date)))
                    :tags tags
                    :description (or (funcall get "DESCRIPTION") "")
                    :thumb (funcall get "THUMB")
                    :first-image (plist-get scan :first-image)
                    :words (plist-get scan :words)
                    :draft draft
                    :url (format "%s/phile/%s/" lameserver--site-url
                                 (lameserver--phile-hex phile)))
              entries)))
    ;; duplicates are a hard error before anything is written
    (let ((seen (make-hash-table)))
      (dolist (e entries)
        (let ((n (plist-get e :phile)))
          (when (gethash n seen)
            (error "lameserver: duplicate phile number %s (%s and %s)"
                   (lameserver--phile-hex n)
                   (plist-get (gethash n seen) :file) (plist-get e :file)))
          (puthash n e seen))))
    (setq lameserver--manifest
          (sort entries (lambda (a b) (> (plist-get a :phile)
                                         (plist-get b :phile)))))))

(defun lameserver--published ()
  "Manifest entries that are not drafts, newest first."
  (cl-remove-if (lambda (e) (plist-get e :draft)) lameserver--manifest))

(defun lameserver--manifest-entry (file)
  (cl-find (file-truename file) lameserver--manifest
           :key (lambda (e) (file-truename (plist-get e :file)))
           :test #'equal))

(defun lameserver--divider (entry)
  (aref lameserver--dividers
        (lameserver--seed (concat (plist-get entry :phile-hex)
                                  (plist-get entry :slug))
                          (length lameserver--dividers))))

;;;; ---------------------------------------------------------------- figlet

(defun lameserver--figlet (title &optional font width)
  "FIGlet-render TITLE; nil when figlet is unavailable.  Cached."
  (when-let* ((figlet (lameserver--tool "figlet")))
    (let* ((font (or font "standard"))
           (width (or width 120))
           (ascii (replace-regexp-in-string "[^\x20-\x7e]" "" title))
           (cache (lameserver--cache
                   "figlet" (concat (secure-hash
                                     'sha1 (format "%s|%s|%d|%s" ascii font width
                                                   lameserver--converter-version))
                                    ".txt"))))
      (if (file-exists-p cache)
          (with-temp-buffer (insert-file-contents cache) (buffer-string))
        (when-let* ((out (lameserver--run figlet "-w" (number-to-string width)
                                          "-f" font ascii)))
          (with-temp-file cache (insert out))
          out)))))

;;;; ---------------------------------------------------------------- diz cards

;; Every phile opens with a FILE_ID.DIZ-style release card: the title as a
;; chunky figlet logo fading down LORD-style, release info rows, all inside
;; a block border drawn in one <pre> so the columns stay true.

(defconst lameserver--diz-ramp ["dz0" "dz1" "dz1" "dz2" "dz2" "dz3"]
  "Vertical color ramp classes, brightest first (see site.css).")

(defun lameserver--diz-ramp-class (i n)
  "Ramp class for row I of N rows, fading down the card."
  (aref lameserver--diz-ramp
        (min (1- (length lameserver--diz-ramp))
             (/ (* i (length lameserver--diz-ramp)) (max 1 n)))))

(defun lameserver--cells-len (cells)
  "Visible length of CELLS, a list of (TEXT CLASS HREF) triples."
  (apply #'+ 0 (mapcar (lambda (c) (length (car c))) cells)))

(defun lameserver--cells-html (cells)
  (mapconcat
   (pcase-lambda (`(,text ,class ,href))
     (let ((esc (lameserver--escape text)))
       (cond (href (format "<a class=\"%s\" href=\"%s\">%s</a>" (or class "") href esc))
             (class (format "<span class=\"%s\">%s</span>" class esc))
             (t esc))))
   cells ""))

(defun lameserver--diz-line (cells inner-w edge-class &optional align)
  "One bordered card row: CELLS padded to INNER-W between █ edges."
  (let* ((len (lameserver--cells-len cells))
         (pad (max 0 (- inner-w len)))
         (lpad (if (eq align 'left) 2 (/ pad 2)))
         (rpad (max 0 (- pad lpad))))
    (concat (format "<span class=\"%s\" aria-hidden=\"true\">█</span>" edge-class)
            (make-string lpad ?\s)
            (lameserver--cells-html cells)
            (make-string rpad ?\s)
            (format "<span class=\"%s\" aria-hidden=\"true\">█</span>" edge-class))))

(defun lameserver--diz-card (entry)
  "The release card for ENTRY: bordered DIZ block + tagline."
  (let* ((title (plist-get entry :title))
         (fig (lameserver--figlet title "chunky" 72))
         (fig-lines (when (and fig (not (string-blank-p fig)))
                      (mapcar #'string-trim-right
                              (split-string (string-trim-right fig) "\n"))))
         (date (if (plist-get entry :time)
                   (format-time-string "%Y-%m-%d" (plist-get entry :time))
                 "undated"))
         (info-cells
          (list (list (format "phile %s" (plist-get entry :phile-hex)) "dc-purple" nil)
                (list " ░ " "dz3" nil)
                (list date nil nil)
                (list " ░ " "dz3" nil)
                (list (format "%d min read" (lameserver--reading-time
                                             (plist-get entry :words)))
                      nil nil)))
         (cred-cells
          (append
           (cl-loop for tag in (plist-get entry :tags)
                    append (list (list (format "[%s]" tag) "tag"
                                       (format "/category/%s/" (lameserver--slugify tag)))
                                 (list " " nil nil)))
           (list (list "░ " "dz3" nil))
           (if-let* ((sig (plist-get entry :sig)))
               (list (list (format "sig ✓ 0x%s" (substring sig -16)) "sig ok" "source.org.asc")
                     (list " " nil nil)
                     (list "[pubkey]" "sig ok" "/pubkey.asc"))
             (list (list "sig: none" "sig none" nil)))))
         (title-cells (list (list (upcase title) "dz0" nil)))
         (fig-w (apply #'max 0 (mapcar #'length (or fig-lines '()))))
         (inner-w (max 46 (+ 4 (max fig-w
                                    (lameserver--cells-len info-cells)
                                    (lameserver--cells-len cred-cells)))))
         (cols (+ inner-w 2))
         ;; row plan: blank, figlet|title, blank, presents, info, creds, blank
         (n-rows (+ 6 (if fig-lines (length fig-lines) 1)))
         (row -1)
         (next-edge (lambda () (lameserver--diz-ramp-class (cl-incf row) n-rows)))
         (lines '()))
    (push (format "<span class=\"dz1\" aria-hidden=\"true\">%s</span>"
                  (make-string cols ?▄))
          lines)
    (push (lameserver--diz-line nil inner-w (funcall next-edge)) lines)
    (if fig-lines
        (let ((nf (length fig-lines)) (fi -1))
          (dolist (fl fig-lines)
            (cl-incf fi)
            ;; pad every line to the logo's full width so per-line
            ;; centering can't shear the letters apart
            (push (lameserver--diz-line
                   (list (list (concat fl (make-string (- fig-w (length fl)) ?\s))
                               (lameserver--diz-ramp-class fi nf) nil))
                   inner-w (funcall next-edge))
                  lines)))
      (push (lameserver--diz-line title-cells inner-w (funcall next-edge)) lines))
    (push (lameserver--diz-line nil inner-w (funcall next-edge)) lines)
    (push (lameserver--diz-line '(("∙ lameserver presents ∙" "dz3" nil))
                                inner-w (funcall next-edge))
          lines)
    (push (lameserver--diz-line info-cells inner-w (funcall next-edge)) lines)
    (push (lameserver--diz-line cred-cells inner-w (funcall next-edge)) lines)
    (push (format "<span class=\"dz3\" aria-hidden=\"true\">%s</span>"
                  (make-string cols ?▀))
          lines)
    (concat
     (format "<h1 class=\"vh\">%s</h1>" (lameserver--escape title))
     (format "<pre class=\"diz\" style=\"--cols:%d\">%s</pre>"
             cols (string-join (nreverse lines) "\n"))
     (let ((desc (plist-get entry :description)))
       (if (string-blank-p (or desc ""))
           ""
         (format "<div class=\"diz-tagline\">.. %s ..</div>"
                 (lameserver--escape desc)))))))

;;;; ---------------------------------------------------------------- ANSI art

(defun lameserver--sgr-parse (ansi)
  "Parse chafa ANSI output into a list of (CHAR FG BG), FG/BG \"r;g;b\" or nil."
  (let ((pos 0) (len (length ansi)) (fg nil) (bg nil) (cells '()))
    (while (< pos len)
      (let ((ch (aref ansi pos)))
        (cond
         ;; CSI sequence: ESC [ params final-byte
         ((and (= ch ?\e) (< (1+ pos) len) (= (aref ansi (1+ pos)) ?\[))
          (let ((end (+ pos 2)))
            (while (and (< end len) (not (<= ?@ (aref ansi end) ?~)))
              (setq end (1+ end)))
            (when (and (< end len) (= (aref ansi end) ?m))
              (let ((params (split-string (substring ansi (+ pos 2) end) ";")))
                (while params
                  (pcase (pop params)
                    ((or "0" "") (setq fg nil bg nil))
                    ("39" (setq fg nil))
                    ("49" (setq bg nil))
                    ("38" (when (equal (car params) "2")
                            (pop params)
                            (setq fg (string-join (list (pop params) (pop params) (pop params)) ";"))))
                    ("48" (when (equal (car params) "2")
                            (pop params)
                            (setq bg (string-join (list (pop params) (pop params) (pop params)) ";"))))
                    (_ nil)))))
            (setq pos (1+ end))))
         ((= ch ?\n) (push (list ?\n nil nil) cells) (setq pos (1+ pos)))
         ((= ch ?\r) (setq pos (1+ pos)))
         (t (push (list ch fg bg) cells) (setq pos (1+ pos))))))
    (nreverse cells)))

(defun lameserver--ansi->html (ansi id font-class)
  "Convert ANSI escapes to an HTML fragment: scoped <style> + <pre>.
Adjacent cells with identical style are merged into one span; colors are
deduplicated into per-image classes to keep the output small."
  (let ((classes (make-hash-table :test 'equal))
        (order '())
        (out '())
        (run '())
        (cur 'none))
    (cl-flet ((esc (c) (pcase c (?& "&amp;") (?< "&lt;") (?> "&gt;")
                         (_ (char-to-string c))))
              (flush ()
                (when run
                  (let ((text (apply #'concat (nreverse run))))
                    (push (if (equal cur '(nil . nil))
                              text
                            (let ((cls (or (gethash cur classes)
                                           (let ((c (format "c%d" (hash-table-count classes))))
                                             (puthash cur c classes)
                                             (push (cons c cur) order)
                                             c))))
                              (format "<span class=\"%s\">%s</span>" cls text)))
                          out))
                  (setq run '()))))
      (dolist (cell (lameserver--sgr-parse ansi))
        (pcase-let ((`(,ch ,fg ,bg) cell))
          (if (= ch ?\n)
              (progn (flush) (setq cur 'none) (push "\n" out))
            (let ((style (cons fg bg)))
              (unless (equal style cur) (flush) (setq cur style))
              (push (esc ch) run)))))
      (flush))
    (let ((css (mapconcat
                (lambda (c)
                  (pcase-let ((`(,name . (,fg . ,bg)) c))
                    ;; chafa params are "r;g;b" — CSS wants commas
                    (format "#%s .%s{%s%s}" id name
                            (if fg (format "color:rgb(%s);"
                                           (subst-char-in-string ?\; ?, fg))
                              "")
                            (if bg (format "background:rgb(%s);"
                                           (subst-char-in-string ?\; ?, bg))
                              ""))))
                (nreverse order) ""))
          (body (string-trim-right (apply #'concat (nreverse out)))))
      (format "<style>%s</style><pre class=\"ansi-art %s\" id=\"%s\">%s</pre>"
              css font-class id body))))

(defun lameserver--chafa (path size symbols)
  "Run chafa on PATH; return raw ANSI string or nil.
Braille gets fg-only dithered output — dot density carries the image;
per-cell backgrounds would wash the dots out on smooth gradients."
  (when-let* ((chafa (lameserver--tool "chafa")))
    (apply #'lameserver--run chafa
           (append (list "--format" "symbols"
                         "--colors" "full"
                         "--symbols" symbols
                         "--size" size)
                   (when (string-match-p "braille" symbols)
                     (list "--fg-only" "--dither" "diffusion"))
                   (list (expand-file-name path))))))

(defun lameserver--ansi-render (path id &optional size symbols)
  "Cached chafa+HTML conversion of image PATH.  Returns HTML or nil."
  (let* ((size (or size (format "%dx999" lameserver--ansi-width)))
         (symbols (or symbols "half+space"))
         (font-class (cond ((string-match-p "braille" symbols) "ansi-braille")
                           ((string-match-p "quad\\|sextant\\|all" symbols) "ansi-argon")
                           (t "ansi-vga")))
         (mtime (file-attribute-modification-time (file-attributes path)))
         (key (secure-hash 'sha1 (format "%s|%s|%s|%s|%s" (expand-file-name path)
                                         (float-time mtime) size symbols
                                         lameserver--converter-version)))
         (cache (lameserver--cache "ansi" (concat key ".html"))))
    (if (file-exists-p cache)
        (let ((html (with-temp-buffer (insert-file-contents cache) (buffer-string))))
          ;; the cached fragment embeds an id; re-target it for this use site
          (replace-regexp-in-string "__ID__" id html t t))
      (when-let* ((ansi (lameserver--chafa path size symbols)))
        (let ((html (lameserver--ansi->html ansi "__ID__" font-class)))
          (when (> (length html) lameserver--ansi-warn-bytes)
            (lameserver--log "lameserver: WARNING %s renders to %dKB of ANSI html"
                             (file-name-nondirectory path) (/ (length html) 1024)))
          (with-temp-file cache (insert html))
          (replace-regexp-in-string "__ID__" id html t t))))))

(defun lameserver--emblem (seed-string &optional w h)
  "Deterministic ANSI block-art emblem for posts without images."
  (let* ((w (or w 22)) (h (or h 11))
         (half (/ (+ w 1) 2))
         (state (string-to-number
                 (substring (secure-hash 'sha1 seed-string) 0 8) 16))
         (chars " ░▒▓█▀▄")
         (rows '()))
    (when (zerop state) (setq state 305419896))
    (dotimes (_y h)
      (let ((cells '()))
        (dotimes (_x half)
          (setq state (lameserver--xorshift state))
          (let* ((c (aref chars (mod state (length chars))))
                 (cls (aref lameserver--emblem-classes
                            (mod (ash state -8) (length lameserver--emblem-classes)))))
            (push (cons c (if (eq c ?\s) nil cls)) cells)))
        ;; mirror for that classic logo symmetry
        (let ((left (reverse cells)))
          (push (append left (cdr (reverse left))) rows))))
    (let ((body
           (mapconcat
            (lambda (row)
              (mapconcat
               (lambda (cell)
                 (if (cdr cell)
                     (format "<span class=\"%s\">%c</span>" (cdr cell) (car cell))
                   (char-to-string (car cell))))
               row ""))
            (nreverse rows) "\n")))
      (format "<pre class=\"ansi-art ansi-vga emblem\" aria-hidden=\"true\">%s</pre>" body))))

;;;; ---------------------------------------------------------------- media urls

(defun lameserver--media-url (path org-file)
  "Site-absolute URL for media PATH referenced from ORG-FILE, or nil."
  (let* ((abs (expand-file-name path (file-name-directory org-file)))
         (media-root (file-truename (lameserver--path "org/media"))))
    (when (string-prefix-p media-root (file-truename abs))
      (concat "/media/" (file-relative-name (file-truename abs) media-root)))))

;;;; ---------------------------------------------------------------- export backend

(defvar lameserver--image-counter 0)

(defun lameserver--attr-plist (element)
  "Read #+ATTR_LAMESERVER plist attached to ELEMENT's paragraph."
  (when-let* ((parent (org-element-lineage element '(paragraph))))
    (org-export-read-attribute :attr_lameserver parent)))

(defun lameserver--image-figure (path org-file attrs)
  "Image as pure ANSI text.  The source raster is a build input only —
nothing but text ships."
  (let* ((width (min lameserver--ansi-max-width
                     (max 20 (or (and (plist-get attrs :width)
                                      (string-to-number (plist-get attrs :width)))
                                 lameserver--ansi-width))))
         (symbols (or (plist-get attrs :symbols) "half+space"))
         (id (format "ansi%d" (cl-incf lameserver--image-counter)))
         (alt (or (plist-get attrs :alt) (file-name-base path)))
         (ansi (lameserver--ansi-render
                (expand-file-name path (file-name-directory org-file))
                id (format "%dx999" width)
                (pcase symbols
                  ("braille" "braille")
                  ("quad" "quad+half+space")
                  (_ symbols)))))
    (if (not ansi)
        (progn
          (lameserver--log "lameserver: WARNING no ANSI renderer — %s dropped" path)
          (format "<pre class=\"ansi-art ansi-missing\">[ image: %s — no renderer at build time ]</pre>"
                  (lameserver--escape (file-name-nondirectory path))))
      (format "<figure class=\"ansi-img\" role=\"img\" aria-label=\"%s\">%s</figure>"
              (lameserver--escape alt) ansi))))

(defun lameserver--av-html (path org-file)
  "Audio/video element inside box-drawing chrome."
  (let ((url (or (lameserver--media-url path org-file) path))
        (ext (downcase (or (file-name-extension path) ""))))
    (format "<div class=\"ansi-frame\">%s</div>"
            (if (member ext '("mp3" "ogg" "flac" "wav"))
                (format "<audio controls preload=\"metadata\" src=\"%s\"></audio>" url)
              (format "<video controls preload=\"metadata\" src=\"%s\"></video>" url)))))

(defun lameserver--html-link (link desc info)
  "Intercept media links; delegate everything else to ox-html."
  (let* ((type (org-element-property :type link))
         (path (org-element-property :path link))
         (ext (downcase (or (file-name-extension (or path "")) "")))
         (org-file (plist-get info :input-file)))
    (cond
     ;; images always become ANSI text — described or not, nothing raster ships
     ((and (string= type "file")
           (member ext '("png" "jpg" "jpeg" "gif" "webp")))
      (lameserver--image-figure path org-file
                                (append (and desc (list :alt desc))
                                        (lameserver--attr-plist link))))
     ((and (string= type "file")
           (member ext '("mp4" "webm" "mp3" "ogg" "flac" "wav")))
      (lameserver--av-html path org-file))
     ;; rewrite plain file links into org/media to their published URL
     ((and (string= type "file") (lameserver--media-url path org-file))
      (format "<a href=\"%s\">%s</a>"
              (lameserver--media-url path org-file) (or desc path)))
     (t (org-html-link link desc info)))))

;;;; ---------------------------------------------------------------- page chrome

(defconst lameserver--menu
  '(("board" . "/board/") ("about" . "/about/") ("rss" . "/feed.xml"))
  "Site menu; the first letter of each label is its live hotkey.")

(defun lameserver--menu-html (active &optional loc)
  "Menu bar; LOC is the BBS-style \"current area\" field, right-aligned."
  (concat
   "<nav class=\"menu\" aria-label=\"site\">"
   (mapconcat
    (lambda (item)
      (let* ((label (car item)) (href (cdr item))
             (hot (substring label 0 1)) (rest (substring label 1)))
        (format "<a href=\"%s\"%s>(<span class=\"hot\">%s</span>)%s</a>"
                href
                (if (equal label active) " class=\"active\"" "")
                hot rest)))
    lameserver--menu " ")
   "<a href=\"/board/#search\">(<span class=\"hot\">/</span>)search</a>"
   (when loc
     (format "<span class=\"menu-loc\" aria-hidden=\"true\">▓▒ %s</span>"
             (lameserver--escape loc)))
   "</nav>"))

(defun lameserver--masthead (right)
  (format (concat "<div class=\"masthead\" aria-hidden=\"true\">"
                  "<span class=\"cap\">░▒▓</span>"
                  "<span class=\"rail\">══[ </span>%s<span class=\"rail\"> ]══</span>"
                  "<span class=\"rail-fill\"></span>"
                  "<span class=\"rail\">══[ </span>%s<span class=\"rail\"> ]══</span>"
                  "<span class=\"cap\">▓▒░</span>"
                  "</div>")
          lameserver--site-name right))

(defun lameserver--footer ()
  (format (concat "<footer class=\"site-footer\">"
                  "<button class=\"foot-rail\" type=\"button\" aria-label=\"hang up\">"
                  "░▒▓█▓▒░ ░▒▓█▓▒░ ░▒▓█▓▒░</button>"
                  "<div class=\"foot-node\" aria-hidden=\"true\">"
                  "<span class=\"chip\">node 1/1</span>"
                  "<span class=\"chip\">38400 8n1</span>"
                  "<span class=\"chip\">ansi</span>"
                  "<span class=\"chip chip-ok\">carrier ok</span>"
                  "</div>"
                  "<p><a href=\"%s\">lameserver.net</a> · last updated %s</p>"
                  "<p class=\"foot-fine\">org-mode → elisp → ANSI · no trackers, no frameworks · "
                  "type set in Monaspace Argon, Px437 IBM VGA (CC BY-SA 4.0 int10h.org), GNU FreeMono</p>"
                  "</footer>")
          lameserver--site-url
          (or lameserver--build-stamp "unknown")))

(defun lameserver--page-shell (&rest args)
  "Full HTML page.  ARGS plist: :title :desc :canonical :masthead-right
:active :loc :body :extra-head :body-script"
  (let ((title (plist-get args :title))
        (desc (or (plist-get args :desc) "lameserver.net — a bulletin board"))
        (canonical (plist-get args :canonical)))
    (concat
     "<!doctype html>\n<html lang=\"en\">\n<head>\n"
     "<meta charset=\"utf-8\">\n"
     "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
     (format "<title>%s</title>\n" (lameserver--escape title))
     (format "<meta name=\"description\" content=\"%s\">\n" (lameserver--escape desc))
     (when canonical
       (format "<link rel=\"canonical\" href=\"%s\">\n" canonical))
     "<link rel=\"alternate\" type=\"application/rss+xml\" title=\"lameserver\" href=\"/feed.xml\">\n"
     "<link rel=\"icon\" href=\"data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'><text y='13' font-size='13' fill='%23ff79c6'>▓</text></svg>\">\n"
     "<link rel=\"stylesheet\" href=\"/assets/css/site.css\">\n"
     "<link rel=\"stylesheet\" href=\"/assets/css/dracula.css\">\n"
     (or (plist-get args :extra-head) "")
     "</head>\n<body>\n"
     "<header class=\"site-header\">"
     "<a class=\"skip\" href=\"#content\">skip to content</a>"
     "<!-- the space above can be used to advertise your lame BBS if you so desire. . .  - stc/acid, 1995 -->"
     "<canvas id=\"banner\" aria-label=\"lameserver\"></canvas>"
     (lameserver--masthead (or (plist-get args :masthead-right) "est. 2026"))
     (lameserver--menu-html (plist-get args :active) (plist-get args :loc))
     "</header>\n"
     "<main id=\"content\">\n"
     (plist-get args :body)
     "\n</main>\n"
     (lameserver--footer)
     "<script src=\"/assets/js/header.js\" defer></script>\n"
     (or (plist-get args :body-script) "")
     "</body>\n</html>\n")))

;;;; ---------------------------------------------------------------- post template

(defun lameserver--reading-time (words)
  (max 1 (round (/ (or words 0) 220.0))))

(defun lameserver--share-html (entry)
  (let* ((url (plist-get entry :url))
         (eurl (url-hexify-string url))
         (etitle (url-hexify-string (plist-get entry :title))))
    (concat
     "<section class=\"share\" aria-label=\"share\">"
     (format "<div class=\"share-rail\" aria-hidden=\"true\">.oO( share this phile )Oo.</div>")
     "<div class=\"share-links\">"
     (format "<a rel=\"noopener\" target=\"_blank\" href=\"https://twitter.com/intent/tweet?url=%s&amp;text=%s\">[x]</a>" eurl etitle)
     (format "<button type=\"button\" class=\"share-fedi\" data-url=\"%s\" data-title=\"%s\">[fedi]</button>"
             (lameserver--escape url) (lameserver--escape (plist-get entry :title)))
     (format "<a rel=\"noopener\" target=\"_blank\" href=\"https://news.ycombinator.com/submitlink?u=%s&amp;t=%s\">[hn]</a>" eurl etitle)
     (format "<a rel=\"noopener\" target=\"_blank\" href=\"https://www.reddit.com/submit?url=%s&amp;title=%s\">[reddit]</a>" eurl etitle)
     (format "<a rel=\"noopener\" target=\"_blank\" href=\"https://lobste.rs/stories/new?url=%s&amp;title=%s\">[lobsters]</a>" eurl etitle)
     (format "<button type=\"button\" class=\"share-copy\" data-url=\"%s\">[copy url]</button>"
             (lameserver--escape url))
     "</div></section>")))

(defun lameserver--neighbor-rail (entry)
  (let* ((posts (lameserver--published))
         (pos (cl-position entry posts :test #'eq))
         (next (and pos (> pos 0) (nth (1- pos) posts)))          ; newer
         (prev (and pos (nth (1+ pos) posts))))                   ; older
    (concat
     "<nav class=\"phile-rail\" aria-label=\"neighboring philes\">"
     (if prev
         (format "<a id=\"prev-phile\" href=\"/phile/%s/\">&#8592; %s %s</a>"
                 (plist-get prev :phile-hex) (plist-get prev :phile-hex)
                 (lameserver--escape (plist-get prev :title)))
       "<span class=\"dim\">&#8592; older: none</span>")
     "<a href=\"/board/\">[board]</a>"
     (if next
         (format "<a id=\"next-phile\" href=\"/phile/%s/\">%s %s &#8594;</a>"
                 (plist-get next :phile-hex) (plist-get next :phile-hex)
                 (lameserver--escape (plist-get next :title)))
       "<span class=\"dim\">newer: none &#8594;</span>")
     "</nav>")))

(defun lameserver--html-template (contents info)
  "Full page for a post (or page) exported through the derived backend."
  (let* ((file (plist-get info :input-file))
         (entry (lameserver--manifest-entry file)))
    (if (null entry)
        ;; a plain page (about etc.): lighter chrome, named in the menu bar
        (let ((title (org-export-data (plist-get info :title) info)))
          (lameserver--page-shell
           :title (format "%s · lameserver" title)
           :active (lameserver--slugify title)
           :loc title
           :body (concat (format "<h1 class=\"vh\">%s</h1>" (lameserver--escape title))
                         "<article class=\"phile-body\">" contents "</article>")
           :body-script "<script src=\"/assets/js/phile.js\" defer></script>"))
      (let ((title (plist-get entry :title))
            (divider (lameserver--divider entry)))
        (lameserver--page-shell
         :title (format "%s · lameserver" title)
         :desc (plist-get entry :description)
         :canonical (plist-get entry :url)
         :masthead-right (format "phile %s of %s"
                                 (plist-get entry :phile-hex)
                                 (lameserver--phile-hex
                                  (plist-get (car (lameserver--published)) :phile)))
         :active "board"
         :loc (format "board › %s" (plist-get entry :phile-hex))
         :body (concat
                (lameserver--diz-card entry)
                "<article class=\"phile-body\">" contents "</article>"
                (format "<div class=\"divider\" aria-hidden=\"true\">%s</div>" divider)
                (lameserver--share-html entry)
                (lameserver--neighbor-rail entry))
         :body-script "<script src=\"/assets/js/phile.js\" defer></script>")))))

(org-export-define-derived-backend 'lameserver-html 'html
  :translate-alist '((template . lameserver--html-template)
                     (link . lameserver--html-link))
  :options-alist '((:phile "PHILE" nil nil t)
                   (:thumb "THUMB" nil nil t)
                   (:draft "DRAFT" nil nil t)))

;;;; ---------------------------------------------------------------- exporting

(defconst lameserver--export-plist
  '(:section-numbers t
    :with-toc nil
    :with-author nil
    :with-email nil
    :with-creator nil
    :with-date nil
    :with-sub-superscript {}
    :html-doctype "html5"
    :html-html5-fancy t))

(defmacro lameserver--with-export-env (&rest body)
  "Run BODY with export options safely scoped (daemon hygiene)."
  `(let ((org-export-use-babel nil)
         (org-confirm-babel-evaluate t)
         (org-html-htmlize-output-type
          (if (require 'htmlize nil t) 'css nil))
         (org-export-with-broken-links 'mark)
         (coding-system-for-write 'utf-8)
         (make-backup-files nil)
         (system-time-locale "C")
         ;; htmlize fontifies src blocks in temp buffers; a daemon's UI mode
         ;; hooks (indent-bars etc.) break or pollute that — export wants
         ;; pure font-lock, so run every mode bare
         (prog-mode-hook nil)
         (text-mode-hook nil)
         (org-mode-hook nil))
     ,@body))

(defun lameserver--export-file (file outfile)
  "Export org FILE to OUTFILE through the lameserver backend."
  (make-directory (file-name-directory outfile) t)
  (let ((visiting (find-buffer-visiting file)))
    (with-current-buffer (or visiting (find-file-noselect file))
      (unwind-protect
          (org-export-to-file 'lameserver-html outfile
            nil nil nil nil lameserver--export-plist)
        (unless visiting (kill-buffer (current-buffer)))))))

(defun lameserver--post-plaintext (file)
  "Plaintext body of FILE for the search index (truncated)."
  (let ((visiting (find-buffer-visiting file)))
    (with-current-buffer (or visiting (find-file-noselect file))
      (unwind-protect
          (let ((txt (org-export-as 'ascii nil nil t
                                    '(:with-toc nil :section-numbers nil))))
            (substring txt 0 (min 2000 (length txt))))
        (unless visiting (kill-buffer (current-buffer)))))))

;;;; ---------------------------------------------------------------- signing

(defun lameserver--sign-posts ()
  "Detach-sign every published phile's org source into its output dir.
Each entry gains :sig (the signing key fingerprint) on success.  Readers
verify with: gpg --verify source.org.asc source.org"
  (if (not (lameserver--tool "gpg"))
      (lameserver--log "lameserver: gpg not found — philes ship unsigned")
    (dolist (e (lameserver--published))
      (let* ((src (plist-get e :file))
             (dir (lameserver--docs "phile" (plist-get e :phile-hex)))
             (dst (expand-file-name "source.org" dir))
             (asc (concat dst ".asc")))
        (make-directory dir t)
        (copy-file src dst t)
        (when (or (not (file-exists-p asc))
                  (file-newer-than-file-p src asc))
          (apply #'lameserver--run "gpg"
                 (append '("--batch" "--yes" "--armor" "--detach-sign")
                         (and lameserver--gpg-key
                              (list "--local-user" lameserver--gpg-key))
                         (list "--output" asc dst))))
        (when (file-exists-p asc)
          (when-let* ((v (lameserver--run "gpg" "--status-fd" "1"
                                          "--verify" asc dst)))
            (when (string-match "VALIDSIG \\([0-9A-F]+\\)" v)
              (plist-put e :sig (match-string 1 v)))))
        (unless (plist-get e :sig)
          (lameserver--log "lameserver: WARNING %s is unsigned"
                           (plist-get e :phile-hex)))))
    ;; ship the public key so signatures are verifiable
    (when-let* ((entry (cl-find-if (lambda (e) (plist-get e :sig))
                                   (lameserver--published)))
                (pub (lameserver--run "gpg" "--armor" "--export"
                                      (plist-get entry :sig))))
      (with-temp-file (lameserver--docs "pubkey.asc") (insert pub)))))

;;;; ---------------------------------------------------------------- thumbs

(defun lameserver--thumb-html (entry)
  "Board-listing thumbnail: #+THUMB, else first image, else emblem."
  (let* ((file (plist-get entry :file))
         (src (or (plist-get entry :thumb) (plist-get entry :first-image)))
         (abs (and src (expand-file-name src (file-name-directory file)))))
    (or (and abs (file-exists-p abs)
             (lameserver--ansi-render
              abs (format "th%s" (plist-get entry :phile-hex))
              lameserver--thumb-size "half+space"))
        (lameserver--emblem (concat (plist-get entry :phile-hex)
                                    (plist-get entry :slug))))))

;;;; ---------------------------------------------------------------- board & categories

(defun lameserver--listing-row (entry)
  "One board entry as a FILE_ID.DIZ-style card: thumb as the logo,
title as the release name, block rules top and bottom."
  (let ((hex (plist-get entry :phile-hex))
        (date (if (plist-get entry :time)
                  (format-time-string "%Y-%m-%d" (plist-get entry :time))
                "undated")))
    (format (concat "<li class=\"row\">"
                    "<span class=\"card-top\" aria-hidden=\"true\">%s</span>"
                    "<span class=\"row-thumb\" aria-hidden=\"true\">%s</span>"
                    "<span class=\"row-head\">"
                    "<a class=\"row-link\" href=\"/phile/%s/\">"
                    "<span class=\"row-hex\">[%s]</span> "
                    "<span class=\"row-title\">%s</span></a>%s</span>"
                    "<span class=\"row-desc\">%s</span>"
                    "<span class=\"row-foot\"><span class=\"row-date\">%s</span>"
                    "<span class=\"row-tags\">%s</span></span>"
                    "<span class=\"card-bot\" aria-hidden=\"true\">%s</span>"
                    "</li>")
            (make-string 80 ?▄)
            (lameserver--thumb-html entry)
            hex
            hex
            (lameserver--escape (plist-get entry :title))
            (if (plist-get entry :sig)
                " <span class=\"sig ok\" title=\"signed\">&#10003;</span>" "")
            (lameserver--escape (plist-get entry :description))
            date
            (mapconcat (lambda (tag)
                         (format "<a class=\"tag\" href=\"/category/%s/\">[%s]</a>"
                                 (lameserver--slugify tag) (lameserver--escape tag)))
                       (plist-get entry :tags) " ")
            (make-string 80 ?▀))))

(defun lameserver--listing-page (title posts out-dir &optional lead)
  (let ((body
         (concat
          (format "<h1 class=\"vh\">%s</h1>" (lameserver--escape title))
          (or lead "")
          "<div class=\"board-bar\"><label id=\"search\" class=\"search-prompt\">"
          "search&gt; <input type=\"search\" id=\"board-search\" autocomplete=\"off\" "
          "spellcheck=\"false\" aria-label=\"search philes\"></label>"
          "<span class=\"board-hint\" aria-hidden=\"true\">j/k move · enter opens · / search · ? help</span></div>"
          "<ul class=\"board\" id=\"board-list\">"
          (mapconcat #'lameserver--listing-row posts "\n")
          "</ul>")))
    (make-directory out-dir t)
    (with-temp-file (expand-file-name "index.html" out-dir)
      (insert (lameserver--page-shell
               :title (format "%s · lameserver" title)
               :active "board"
               :loc title
               :masthead-right (format "%d philes on file" (length posts))
               :body body
               :body-script "<script src=\"/assets/js/board.js\" defer></script>")))))

(defun lameserver--write-board ()
  (lameserver--listing-page "the board" (lameserver--published)
                            (lameserver--docs "board")))

(defun lameserver--all-tags ()
  (let ((tags '()))
    (dolist (e (lameserver--published))
      (dolist (tag (plist-get e :tags))
        (cl-pushnew tag tags :test #'equal)))
    (sort tags #'string<)))

(defun lameserver--write-categories ()
  (dolist (tag (lameserver--all-tags))
    (let ((posts (cl-remove-if-not
                  (lambda (e) (member tag (plist-get e :tags)))
                  (lameserver--published))))
      (lameserver--listing-page
       (format "category: %s" tag) posts
       (lameserver--docs "category" (lameserver--slugify tag))
       (format "<p class=\"lead\"><a href=\"/board/\">&#8592; all philes</a></p>")))))

;;;; ---------------------------------------------------------------- feed & search

(defun lameserver--rfc822 (time)
  (let ((system-time-locale "C"))
    (format-time-string "%a, %d %b %Y %H:%M:%S %z" (or time (current-time)))))

(defun lameserver--write-feed ()
  (with-temp-file (lameserver--docs "feed.xml")
    (insert "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            "<rss version=\"2.0\" xmlns:atom=\"http://www.w3.org/2005/Atom\">\n<channel>\n"
            "<title>lameserver</title>\n"
            (format "<link>%s/</link>\n" lameserver--site-url)
            "<description>philes from the board at lameserver.net</description>\n"
            (format "<atom:link href=\"%s/feed.xml\" rel=\"self\" type=\"application/rss+xml\"/>\n"
                    lameserver--site-url)
            (format "<lastBuildDate>%s</lastBuildDate>\n" (lameserver--rfc822 nil)))
    (dolist (e (lameserver--published))
      (insert "<item>\n"
              (format "<title>%s</title>\n" (lameserver--escape (plist-get e :title)))
              (format "<link>%s</link>\n" (plist-get e :url))
              (format "<guid isPermaLink=\"true\">%s</guid>\n" (plist-get e :url))
              (format "<pubDate>%s</pubDate>\n" (lameserver--rfc822 (plist-get e :time)))
              (format "<description>%s</description>\n"
                      (lameserver--escape (plist-get e :description)))
              "</item>\n"))
    (insert "</channel>\n</rss>\n")))

(defun lameserver--write-search-json ()
  (let ((items
         (mapcar
          (lambda (e)
            `((phile . ,(plist-get e :phile-hex))
              (title . ,(plist-get e :title))
              (url . ,(format "/phile/%s/" (plist-get e :phile-hex)))
              (date . ,(if (plist-get e :time)
                           (format-time-string "%Y-%m-%d" (plist-get e :time))
                         ""))
              (tags . ,(vconcat (or (plist-get e :tags) [])))
              (description . ,(plist-get e :description))
              (text . ,(or (ignore-errors
                             (lameserver--post-plaintext (plist-get e :file)))
                           ""))))
          (lameserver--published))))
    (with-temp-file (lameserver--docs "search.json")
      (insert (json-serialize (vconcat items))))))

;;;; ---------------------------------------------------------------- static & prune

(defun lameserver--copy-tree (src dst)
  (when (file-directory-p dst) (delete-directory dst t))
  (when (file-directory-p src) (copy-directory src dst t t t)))

(defun lameserver--write-static ()
  ;; assets (minus static/) -> docs/assets.  Media: only audio/video ship —
  ;; images exist solely as build inputs for the ANSI conversion.
  (let ((tmp-static (lameserver--path "assets/static")))
    (lameserver--copy-tree (lameserver--path "assets") (lameserver--docs "assets"))
    (delete-directory (lameserver--docs "assets/static") t)
    (lameserver--copy-tree (lameserver--path "org/media") (lameserver--docs "media"))
    (dolist (img (ignore-errors
                   (directory-files-recursively
                    (lameserver--docs "media")
                    "\\.\\(?:png\\|jpe?g\\|gif\\|webp\\|svg\\)\\'")))
      (delete-file img))
    ;; splash + CNAME + .nojekyll at the docs root
    (copy-file (expand-file-name "index.html" tmp-static)
               (lameserver--docs "index.html") t)
    (copy-file (expand-file-name "CNAME" tmp-static)
               (lameserver--docs "CNAME") t)
    (with-temp-file (lameserver--docs ".nojekyll"))))

(defun lameserver--prune ()
  "Delete published dirs whose source is gone or re-drafted."
  (let ((live-philes (mapcar (lambda (e) (plist-get e :phile-hex))
                             (lameserver--published)))
        (live-tags (mapcar #'lameserver--slugify (lameserver--all-tags))))
    (dolist (dir (ignore-errors
                   (directory-files (lameserver--docs "phile") t "\\`0x")))
      (unless (member (file-name-nondirectory dir) live-philes)
        (lameserver--log "lameserver: pruning %s" dir)
        (delete-directory dir t)))
    (dolist (dir (ignore-errors
                   (directory-files (lameserver--docs "category") t "\\`[^.]")))
      (unless (member (file-name-nondirectory dir) live-tags)
        (lameserver--log "lameserver: pruning %s" dir)
        (delete-directory dir t)))))

;;;; ---------------------------------------------------------------- orchestrator

(defun lameserver-publish ()
  "Build the whole site into docs/."
  (interactive)
  (let ((t0 (current-time)))
    (setq lameserver--build-stamp
          (let ((system-time-locale "C"))
            (format-time-string "%Y-%m-%d %H:%M UTC" nil t))
          lameserver--image-counter 0)
    (lameserver--scan-posts)
    (lameserver--with-export-env
     (unless (lameserver--tool "chafa")
       (lameserver--log "lameserver: chafa not found — images ship as plain <img>"))
     (unless (lameserver--tool "figlet")
       (lameserver--log "lameserver: figlet not found — titles ship as styled <h1>"))
     (unless (featurep 'htmlize)
       (lameserver--log "lameserver: htmlize not found — code blocks unfontified"))
     (lameserver--write-static)
     (lameserver--sign-posts)
     (dolist (e (lameserver--published))
       (lameserver--export-file
        (plist-get e :file)
        (lameserver--docs "phile" (plist-get e :phile-hex) "index.html")))
     (dolist (page (ignore-errors
                     (directory-files (lameserver--path "org/pages") t "\\.org\\'")))
       (lameserver--export-file
        page (lameserver--docs (file-name-base page) "index.html")))
     (lameserver--write-board)
     (lameserver--write-categories)
     (lameserver--write-feed)
     (lameserver--write-search-json)
     (lameserver--prune))
    (lameserver--log "lameserver: built %d philes in %.1fs"
                     (length (lameserver--published))
                     (float-time (time-subtract (current-time) t0)))))

(defun lameserver-publish-batch ()
  "Batch entry point: build and exit non-zero on error."
  (lameserver-publish))

(defun lameserver-deploy ()
  "Build, commit, and push."
  (interactive)
  (lameserver-publish)
  (let ((default-directory lameserver--root))
    (if (string-blank-p (or (lameserver--run "git" "status" "--porcelain") ""))
        (lameserver--log "lameserver: nothing to deploy — tree is clean")
      (or (and (lameserver--run "git" "add" "-A" "--" "org" "assets" "docs"
                                "publish.el" ".dir-locals.el" ".gitignore")
               (lameserver--run "git" "commit" "-m"
                                (format "publish: %s" lameserver--build-stamp))
               (lameserver--run "git" "push")
               (prog1 t
                 (lameserver--log "lameserver: deployed → %s/board/" lameserver--site-url)))
          (user-error "lameserver: deploy failed — see *lameserver-log*")))))

(defun lameserver-clean ()
  "Delete docs/ and .cache/ after confirming."
  (interactive)
  (when (or noninteractive
            (yes-or-no-p "Delete docs/ and .cache/ entirely? "))
    (dolist (d (list (lameserver--docs) (lameserver--path ".cache")))
      (when (file-directory-p d) (delete-directory d t)))
    (lameserver--log "lameserver: clean")))

(provide 'lameserver-publish)
;;; publish.el ends here
